<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet/wallet.proto

namespace Wallet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wallet.GetUserWalletsResponse</code>
 */
class GetUserWalletsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .wallet.Wallet wallets = 1;</code>
     */
    private $wallets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Wallet\Wallet>|\Google\Protobuf\Internal\RepeatedField $wallets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .wallet.Wallet wallets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWallets()
    {
        return $this->wallets;
    }

    /**
     * Generated from protobuf field <code>repeated .wallet.Wallet wallets = 1;</code>
     * @param array<\Wallet\Wallet>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWallets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wallet\Wallet::class);
        $this->wallets = $arr;

        return $this;
    }

}

