<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet/wallet.proto

namespace Wallet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wallet.GetWalletTypesResponse</code>
 */
class GetWalletTypesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .wallet.WalletTypeDetail wallet_types = 1;</code>
     */
    private $wallet_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Wallet\WalletTypeDetail>|\Google\Protobuf\Internal\RepeatedField $wallet_types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Wallet\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .wallet.WalletTypeDetail wallet_types = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWalletTypes()
    {
        return $this->wallet_types;
    }

    /**
     * Generated from protobuf field <code>repeated .wallet.WalletTypeDetail wallet_types = 1;</code>
     * @param array<\Wallet\WalletTypeDetail>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWalletTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Wallet\WalletTypeDetail::class);
        $this->wallet_types = $arr;

        return $this;
    }

}

