<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.CategoryTransactionItem</code>
 */
class CategoryTransactionItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transaction_id = 1;</code>
     */
    protected $transaction_id = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string transaction_date = 3;</code>
     */
    protected $transaction_date = '';
    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string wallet_name = 5;</code>
     */
    protected $wallet_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transaction_id
     *     @type string $description
     *     @type string $transaction_date
     *     @type float $amount
     *     @type string $wallet_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 1;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_date = 3;</code>
     * @return string
     */
    public function getTransactionDate()
    {
        return $this->transaction_date;
    }

    /**
     * Generated from protobuf field <code>string transaction_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_name = 5;</code>
     * @return string
     */
    public function getWalletName()
    {
        return $this->wallet_name;
    }

    /**
     * Generated from protobuf field <code>string wallet_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletName($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_name = $var;

        return $this;
    }

}

