// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: dashboard/dashboard.proto

package dashboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_dashboard_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *UserID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_dashboard_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DateRange) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *DateRange) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type DateOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,4,opt,name=day,proto3" json:"day,omitempty"`
	Range         *DateRange             `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateOption) Reset() {
	*x = DateOption{}
	mi := &file_dashboard_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateOption) ProtoMessage() {}

func (x *DateOption) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateOption.ProtoReflect.Descriptor instead.
func (*DateOption) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DateOption) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DateOption) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *DateOption) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *DateOption) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *DateOption) GetRange() *DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type GetUserTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	DateOption    *DateOption            `protobuf:"bytes,3,opt,name=date_option,json=dateOption,proto3" json:"date_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTransactionsRequest) Reset() {
	*x = GetUserTransactionsRequest{}
	mi := &file_dashboard_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTransactionsRequest) ProtoMessage() {}

func (x *GetUserTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTransactionsRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetUserTransactionsRequest) GetDateOption() *DateOption {
	if x != nil {
		return x.DateOption
	}
	return nil
}

type TransactionCategory struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CategoryId         string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryType       string                 `protobuf:"bytes,3,opt,name=category_type,json=categoryType,proto3" json:"category_type,omitempty"`
	TotalAmount        float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalTransactions  int32                  `protobuf:"varint,5,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	ParentCategoryName string                 `protobuf:"bytes,6,opt,name=parent_category_name,json=parentCategoryName,proto3" json:"parent_category_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransactionCategory) Reset() {
	*x = TransactionCategory{}
	mi := &file_dashboard_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCategory) ProtoMessage() {}

func (x *TransactionCategory) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCategory.ProtoReflect.Descriptor instead.
func (*TransactionCategory) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionCategory) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *TransactionCategory) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *TransactionCategory) GetCategoryType() string {
	if x != nil {
		return x.CategoryType
	}
	return ""
}

func (x *TransactionCategory) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *TransactionCategory) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionCategory) GetParentCategoryName() string {
	if x != nil {
		return x.ParentCategoryName
	}
	return ""
}

type GetUserTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*TransactionCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTransactionsResponse) Reset() {
	*x = GetUserTransactionsResponse{}
	mi := &file_dashboard_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTransactionsResponse) ProtoMessage() {}

func (x *GetUserTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserTransactionsResponse) GetCategories() []*TransactionCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetCategoryTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	DateOption    *DateOption            `protobuf:"bytes,4,opt,name=date_option,json=dateOption,proto3" json:"date_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryTransactionsRequest) Reset() {
	*x = GetCategoryTransactionsRequest{}
	mi := &file_dashboard_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTransactionsRequest) ProtoMessage() {}

func (x *GetCategoryTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetCategoryTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCategoryTransactionsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetCategoryTransactionsRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetCategoryTransactionsRequest) GetDateOption() *DateOption {
	if x != nil {
		return x.DateOption
	}
	return nil
}

type CategoryTransactionItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TransactionDate string                 `protobuf:"bytes,3,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletName      string                 `protobuf:"bytes,5,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CategoryTransactionItem) Reset() {
	*x = CategoryTransactionItem{}
	mi := &file_dashboard_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryTransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryTransactionItem) ProtoMessage() {}

func (x *CategoryTransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryTransactionItem.ProtoReflect.Descriptor instead.
func (*CategoryTransactionItem) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryTransactionItem) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CategoryTransactionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryTransactionItem) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *CategoryTransactionItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CategoryTransactionItem) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

type GetCategoryTransactionsResponse struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	CategoryId         string                     `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                     `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryType       string                     `protobuf:"bytes,3,opt,name=category_type,json=categoryType,proto3" json:"category_type,omitempty"`
	ParentCategoryName string                     `protobuf:"bytes,4,opt,name=parent_category_name,json=parentCategoryName,proto3" json:"parent_category_name,omitempty"`
	Transactions       []*CategoryTransactionItem `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCategoryTransactionsResponse) Reset() {
	*x = GetCategoryTransactionsResponse{}
	mi := &file_dashboard_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTransactionsResponse) ProtoMessage() {}

func (x *GetCategoryTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *GetCategoryTransactionsResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetCategoryTransactionsResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *GetCategoryTransactionsResponse) GetCategoryType() string {
	if x != nil {
		return x.CategoryType
	}
	return ""
}

func (x *GetCategoryTransactionsResponse) GetParentCategoryName() string {
	if x != nil {
		return x.ParentCategoryName
	}
	return ""
}

func (x *GetCategoryTransactionsResponse) GetTransactions() []*CategoryTransactionItem {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Aggregation   string                 `protobuf:"bytes,3,opt,name=aggregation,proto3" json:"aggregation,omitempty"` // "daily" | "weekly" | "monthly"
	Range         *DateRange             `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	mi := &file_dashboard_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetUserBalanceRequest) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

func (x *GetUserBalanceRequest) GetRange() *DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type BalanceSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WalletId         string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	WalletName       string                 `protobuf:"bytes,2,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	Date             string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Year             int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Month            int32                  `protobuf:"varint,5,opt,name=month,proto3" json:"month,omitempty"`
	Week             int32                  `protobuf:"varint,6,opt,name=week,proto3" json:"week,omitempty"`
	Day              int32                  `protobuf:"varint,7,opt,name=day,proto3" json:"day,omitempty"`
	OpeningBalance   float64                `protobuf:"fixed64,8,opt,name=opening_balance,json=openingBalance,proto3" json:"opening_balance,omitempty"`
	ClosingBalance   float64                `protobuf:"fixed64,9,opt,name=closing_balance,json=closingBalance,proto3" json:"closing_balance,omitempty"`
	TotalIncome      float64                `protobuf:"fixed64,10,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense     float64                `protobuf:"fixed64,11,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	NetChange        float64                `protobuf:"fixed64,12,opt,name=net_change,json=netChange,proto3" json:"net_change,omitempty"`
	TransactionCount int32                  `protobuf:"varint,13,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceSnapshot) Reset() {
	*x = BalanceSnapshot{}
	mi := &file_dashboard_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceSnapshot) ProtoMessage() {}

func (x *BalanceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceSnapshot.ProtoReflect.Descriptor instead.
func (*BalanceSnapshot) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceSnapshot) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *BalanceSnapshot) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *BalanceSnapshot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BalanceSnapshot) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BalanceSnapshot) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *BalanceSnapshot) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *BalanceSnapshot) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *BalanceSnapshot) GetOpeningBalance() float64 {
	if x != nil {
		return x.OpeningBalance
	}
	return 0
}

func (x *BalanceSnapshot) GetClosingBalance() float64 {
	if x != nil {
		return x.ClosingBalance
	}
	return 0
}

func (x *BalanceSnapshot) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *BalanceSnapshot) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *BalanceSnapshot) GetNetChange() float64 {
	if x != nil {
		return x.NetChange
	}
	return 0
}

func (x *BalanceSnapshot) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type GetUserBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*BalanceSnapshot     `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceResponse) Reset() {
	*x = GetUserBalanceResponse{}
	mi := &file_dashboard_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceResponse) ProtoMessage() {}

func (x *GetUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserBalanceResponse) GetSnapshots() []*BalanceSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type GetUserFinancialSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Range         *DateRange             `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFinancialSummaryRequest) Reset() {
	*x = GetUserFinancialSummaryRequest{}
	mi := &file_dashboard_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFinancialSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFinancialSummaryRequest) ProtoMessage() {}

func (x *GetUserFinancialSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFinancialSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUserFinancialSummaryRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserFinancialSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFinancialSummaryRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetUserFinancialSummaryRequest) GetRange() *DateRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type CategorySummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CategoryId       string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName     string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Amount           float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Percentage       float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	TransactionCount int32                  `protobuf:"varint,5,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CategorySummary) Reset() {
	*x = CategorySummary{}
	mi := &file_dashboard_dashboard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySummary) ProtoMessage() {}

func (x *CategorySummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySummary.ProtoReflect.Descriptor instead.
func (*CategorySummary) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{13}
}

func (x *CategorySummary) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategorySummary) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategorySummary) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CategorySummary) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *CategorySummary) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type WalletSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WalletId          string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	WalletName        string                 `protobuf:"bytes,2,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	WalletType        string                 `protobuf:"bytes,3,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	OpeningBalance    float64                `protobuf:"fixed64,4,opt,name=opening_balance,json=openingBalance,proto3" json:"opening_balance,omitempty"`
	ClosingBalance    float64                `protobuf:"fixed64,5,opt,name=closing_balance,json=closingBalance,proto3" json:"closing_balance,omitempty"`
	Income            float64                `protobuf:"fixed64,6,opt,name=income,proto3" json:"income,omitempty"`
	Expense           float64                `protobuf:"fixed64,7,opt,name=expense,proto3" json:"expense,omitempty"`
	NetChange         float64                `protobuf:"fixed64,8,opt,name=net_change,json=netChange,proto3" json:"net_change,omitempty"`
	ShareOfBalancePct float64                `protobuf:"fixed64,9,opt,name=share_of_balance_pct,json=shareOfBalancePct,proto3" json:"share_of_balance_pct,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WalletSummary) Reset() {
	*x = WalletSummary{}
	mi := &file_dashboard_dashboard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletSummary) ProtoMessage() {}

func (x *WalletSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletSummary.ProtoReflect.Descriptor instead.
func (*WalletSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{14}
}

func (x *WalletSummary) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletSummary) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *WalletSummary) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *WalletSummary) GetOpeningBalance() float64 {
	if x != nil {
		return x.OpeningBalance
	}
	return 0
}

func (x *WalletSummary) GetClosingBalance() float64 {
	if x != nil {
		return x.ClosingBalance
	}
	return 0
}

func (x *WalletSummary) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *WalletSummary) GetExpense() float64 {
	if x != nil {
		return x.Expense
	}
	return 0
}

func (x *WalletSummary) GetNetChange() float64 {
	if x != nil {
		return x.NetChange
	}
	return 0
}

func (x *WalletSummary) GetShareOfBalancePct() float64 {
	if x != nil {
		return x.ShareOfBalancePct
	}
	return 0
}

type InvestmentSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalInvested         float64                `protobuf:"fixed64,1,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	TotalCurrentValuation float64                `protobuf:"fixed64,2,opt,name=total_current_valuation,json=totalCurrentValuation,proto3" json:"total_current_valuation,omitempty"`
	TotalSoldAmount       float64                `protobuf:"fixed64,3,opt,name=total_sold_amount,json=totalSoldAmount,proto3" json:"total_sold_amount,omitempty"`
	TotalDeficit          float64                `protobuf:"fixed64,4,opt,name=total_deficit,json=totalDeficit,proto3" json:"total_deficit,omitempty"`
	UnrealizedGain        float64                `protobuf:"fixed64,5,opt,name=unrealized_gain,json=unrealizedGain,proto3" json:"unrealized_gain,omitempty"`
	RealizedGain          float64                `protobuf:"fixed64,6,opt,name=realized_gain,json=realizedGain,proto3" json:"realized_gain,omitempty"`
	InvestmentGrowthPct   float64                `protobuf:"fixed64,7,opt,name=investment_growth_pct,json=investmentGrowthPct,proto3" json:"investment_growth_pct,omitempty"`
	BuyCount              int32                  `protobuf:"varint,8,opt,name=buy_count,json=buyCount,proto3" json:"buy_count,omitempty"`
	SellCount             int32                  `protobuf:"varint,9,opt,name=sell_count,json=sellCount,proto3" json:"sell_count,omitempty"`
	ActivePositions       int32                  `protobuf:"varint,10,opt,name=active_positions,json=activePositions,proto3" json:"active_positions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InvestmentSummary) Reset() {
	*x = InvestmentSummary{}
	mi := &file_dashboard_dashboard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentSummary) ProtoMessage() {}

func (x *InvestmentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentSummary.ProtoReflect.Descriptor instead.
func (*InvestmentSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{15}
}

func (x *InvestmentSummary) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *InvestmentSummary) GetTotalCurrentValuation() float64 {
	if x != nil {
		return x.TotalCurrentValuation
	}
	return 0
}

func (x *InvestmentSummary) GetTotalSoldAmount() float64 {
	if x != nil {
		return x.TotalSoldAmount
	}
	return 0
}

func (x *InvestmentSummary) GetTotalDeficit() float64 {
	if x != nil {
		return x.TotalDeficit
	}
	return 0
}

func (x *InvestmentSummary) GetUnrealizedGain() float64 {
	if x != nil {
		return x.UnrealizedGain
	}
	return 0
}

func (x *InvestmentSummary) GetRealizedGain() float64 {
	if x != nil {
		return x.RealizedGain
	}
	return 0
}

func (x *InvestmentSummary) GetInvestmentGrowthPct() float64 {
	if x != nil {
		return x.InvestmentGrowthPct
	}
	return 0
}

func (x *InvestmentSummary) GetBuyCount() int32 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

func (x *InvestmentSummary) GetSellCount() int32 {
	if x != nil {
		return x.SellCount
	}
	return 0
}

func (x *InvestmentSummary) GetActivePositions() int32 {
	if x != nil {
		return x.ActivePositions
	}
	return 0
}

type NetWorthSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Total             float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	WalletPortion     float64                `protobuf:"fixed64,2,opt,name=wallet_portion,json=walletPortion,proto3" json:"wallet_portion,omitempty"`
	InvestmentPortion float64                `protobuf:"fixed64,3,opt,name=investment_portion,json=investmentPortion,proto3" json:"investment_portion,omitempty"`
	NetWorthPrev      float64                `protobuf:"fixed64,4,opt,name=net_worth_prev,json=netWorthPrev,proto3" json:"net_worth_prev,omitempty"`
	NetWorthGrowthPct float64                `protobuf:"fixed64,5,opt,name=net_worth_growth_pct,json=netWorthGrowthPct,proto3" json:"net_worth_growth_pct,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetWorthSummary) Reset() {
	*x = NetWorthSummary{}
	mi := &file_dashboard_dashboard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthSummary) ProtoMessage() {}

func (x *NetWorthSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthSummary.ProtoReflect.Descriptor instead.
func (*NetWorthSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{16}
}

func (x *NetWorthSummary) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NetWorthSummary) GetWalletPortion() float64 {
	if x != nil {
		return x.WalletPortion
	}
	return 0
}

func (x *NetWorthSummary) GetInvestmentPortion() float64 {
	if x != nil {
		return x.InvestmentPortion
	}
	return 0
}

func (x *NetWorthSummary) GetNetWorthPrev() float64 {
	if x != nil {
		return x.NetWorthPrev
	}
	return 0
}

func (x *NetWorthSummary) GetNetWorthGrowthPct() float64 {
	if x != nil {
		return x.NetWorthGrowthPct
	}
	return 0
}

type FinancialSummary struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeriodType  string                 `protobuf:"bytes,2,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	PeriodKey   string                 `protobuf:"bytes,3,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`
	PeriodStart string                 `protobuf:"bytes,4,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd   string                 `protobuf:"bytes,5,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	// Current period values
	IncomeNow  float64 `protobuf:"fixed64,6,opt,name=income_now,json=incomeNow,proto3" json:"income_now,omitempty"`
	ExpenseNow float64 `protobuf:"fixed64,7,opt,name=expense_now,json=expenseNow,proto3" json:"expense_now,omitempty"`
	ProfitNow  float64 `protobuf:"fixed64,8,opt,name=profit_now,json=profitNow,proto3" json:"profit_now,omitempty"`
	BalanceNow float64 `protobuf:"fixed64,9,opt,name=balance_now,json=balanceNow,proto3" json:"balance_now,omitempty"`
	// Previous period values
	IncomePrev  float64 `protobuf:"fixed64,10,opt,name=income_prev,json=incomePrev,proto3" json:"income_prev,omitempty"`
	ExpensePrev float64 `protobuf:"fixed64,11,opt,name=expense_prev,json=expensePrev,proto3" json:"expense_prev,omitempty"`
	ProfitPrev  float64 `protobuf:"fixed64,12,opt,name=profit_prev,json=profitPrev,proto3" json:"profit_prev,omitempty"`
	BalancePrev float64 `protobuf:"fixed64,13,opt,name=balance_prev,json=balancePrev,proto3" json:"balance_prev,omitempty"`
	// Growth percentages
	IncomeGrowthPct  float64 `protobuf:"fixed64,14,opt,name=income_growth_pct,json=incomeGrowthPct,proto3" json:"income_growth_pct,omitempty"`
	ExpenseGrowthPct float64 `protobuf:"fixed64,15,opt,name=expense_growth_pct,json=expenseGrowthPct,proto3" json:"expense_growth_pct,omitempty"`
	ProfitGrowthPct  float64 `protobuf:"fixed64,16,opt,name=profit_growth_pct,json=profitGrowthPct,proto3" json:"profit_growth_pct,omitempty"`
	BalanceGrowthPct float64 `protobuf:"fixed64,17,opt,name=balance_growth_pct,json=balanceGrowthPct,proto3" json:"balance_growth_pct,omitempty"`
	// Ratios & health indicators
	SavingsRate          float64 `protobuf:"fixed64,18,opt,name=savings_rate,json=savingsRate,proto3" json:"savings_rate,omitempty"`
	ExpenseToIncomeRatio float64 `protobuf:"fixed64,19,opt,name=expense_to_income_ratio,json=expenseToIncomeRatio,proto3" json:"expense_to_income_ratio,omitempty"`
	BurnRateDaily        float64 `protobuf:"fixed64,20,opt,name=burn_rate_daily,json=burnRateDaily,proto3" json:"burn_rate_daily,omitempty"`
	AvgIncomeDaily       float64 `protobuf:"fixed64,21,opt,name=avg_income_daily,json=avgIncomeDaily,proto3" json:"avg_income_daily,omitempty"`
	AvgExpenseDaily      float64 `protobuf:"fixed64,22,opt,name=avg_expense_daily,json=avgExpenseDaily,proto3" json:"avg_expense_daily,omitempty"`
	RunwayDays           float64 `protobuf:"fixed64,23,opt,name=runway_days,json=runwayDays,proto3" json:"runway_days,omitempty"`
	// Transaction stats
	TotalTransactions       int32   `protobuf:"varint,24,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	IncomeTransactionCount  int32   `protobuf:"varint,25,opt,name=income_transaction_count,json=incomeTransactionCount,proto3" json:"income_transaction_count,omitempty"`
	ExpenseTransactionCount int32   `protobuf:"varint,26,opt,name=expense_transaction_count,json=expenseTransactionCount,proto3" json:"expense_transaction_count,omitempty"`
	AvgTransactionAmount    float64 `protobuf:"fixed64,27,opt,name=avg_transaction_amount,json=avgTransactionAmount,proto3" json:"avg_transaction_amount,omitempty"`
	LargestIncome           float64 `protobuf:"fixed64,28,opt,name=largest_income,json=largestIncome,proto3" json:"largest_income,omitempty"`
	LargestExpense          float64 `protobuf:"fixed64,29,opt,name=largest_expense,json=largestExpense,proto3" json:"largest_expense,omitempty"`
	// Nested summaries
	InvestmentSummary *InvestmentSummary `protobuf:"bytes,30,opt,name=investment_summary,json=investmentSummary,proto3" json:"investment_summary,omitempty"`
	NetWorth          *NetWorthSummary   `protobuf:"bytes,31,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	// Top categories
	TopExpenseCategories []*CategorySummary `protobuf:"bytes,32,rep,name=top_expense_categories,json=topExpenseCategories,proto3" json:"top_expense_categories,omitempty"`
	TopIncomeCategories  []*CategorySummary `protobuf:"bytes,33,rep,name=top_income_categories,json=topIncomeCategories,proto3" json:"top_income_categories,omitempty"`
	// Per wallet breakdown
	WalletSummaries []*WalletSummary `protobuf:"bytes,34,rep,name=wallet_summaries,json=walletSummaries,proto3" json:"wallet_summaries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FinancialSummary) Reset() {
	*x = FinancialSummary{}
	mi := &file_dashboard_dashboard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialSummary) ProtoMessage() {}

func (x *FinancialSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialSummary.ProtoReflect.Descriptor instead.
func (*FinancialSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{17}
}

func (x *FinancialSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FinancialSummary) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *FinancialSummary) GetPeriodKey() string {
	if x != nil {
		return x.PeriodKey
	}
	return ""
}

func (x *FinancialSummary) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *FinancialSummary) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *FinancialSummary) GetIncomeNow() float64 {
	if x != nil {
		return x.IncomeNow
	}
	return 0
}

func (x *FinancialSummary) GetExpenseNow() float64 {
	if x != nil {
		return x.ExpenseNow
	}
	return 0
}

func (x *FinancialSummary) GetProfitNow() float64 {
	if x != nil {
		return x.ProfitNow
	}
	return 0
}

func (x *FinancialSummary) GetBalanceNow() float64 {
	if x != nil {
		return x.BalanceNow
	}
	return 0
}

func (x *FinancialSummary) GetIncomePrev() float64 {
	if x != nil {
		return x.IncomePrev
	}
	return 0
}

func (x *FinancialSummary) GetExpensePrev() float64 {
	if x != nil {
		return x.ExpensePrev
	}
	return 0
}

func (x *FinancialSummary) GetProfitPrev() float64 {
	if x != nil {
		return x.ProfitPrev
	}
	return 0
}

func (x *FinancialSummary) GetBalancePrev() float64 {
	if x != nil {
		return x.BalancePrev
	}
	return 0
}

func (x *FinancialSummary) GetIncomeGrowthPct() float64 {
	if x != nil {
		return x.IncomeGrowthPct
	}
	return 0
}

func (x *FinancialSummary) GetExpenseGrowthPct() float64 {
	if x != nil {
		return x.ExpenseGrowthPct
	}
	return 0
}

func (x *FinancialSummary) GetProfitGrowthPct() float64 {
	if x != nil {
		return x.ProfitGrowthPct
	}
	return 0
}

func (x *FinancialSummary) GetBalanceGrowthPct() float64 {
	if x != nil {
		return x.BalanceGrowthPct
	}
	return 0
}

func (x *FinancialSummary) GetSavingsRate() float64 {
	if x != nil {
		return x.SavingsRate
	}
	return 0
}

func (x *FinancialSummary) GetExpenseToIncomeRatio() float64 {
	if x != nil {
		return x.ExpenseToIncomeRatio
	}
	return 0
}

func (x *FinancialSummary) GetBurnRateDaily() float64 {
	if x != nil {
		return x.BurnRateDaily
	}
	return 0
}

func (x *FinancialSummary) GetAvgIncomeDaily() float64 {
	if x != nil {
		return x.AvgIncomeDaily
	}
	return 0
}

func (x *FinancialSummary) GetAvgExpenseDaily() float64 {
	if x != nil {
		return x.AvgExpenseDaily
	}
	return 0
}

func (x *FinancialSummary) GetRunwayDays() float64 {
	if x != nil {
		return x.RunwayDays
	}
	return 0
}

func (x *FinancialSummary) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *FinancialSummary) GetIncomeTransactionCount() int32 {
	if x != nil {
		return x.IncomeTransactionCount
	}
	return 0
}

func (x *FinancialSummary) GetExpenseTransactionCount() int32 {
	if x != nil {
		return x.ExpenseTransactionCount
	}
	return 0
}

func (x *FinancialSummary) GetAvgTransactionAmount() float64 {
	if x != nil {
		return x.AvgTransactionAmount
	}
	return 0
}

func (x *FinancialSummary) GetLargestIncome() float64 {
	if x != nil {
		return x.LargestIncome
	}
	return 0
}

func (x *FinancialSummary) GetLargestExpense() float64 {
	if x != nil {
		return x.LargestExpense
	}
	return 0
}

func (x *FinancialSummary) GetInvestmentSummary() *InvestmentSummary {
	if x != nil {
		return x.InvestmentSummary
	}
	return nil
}

func (x *FinancialSummary) GetNetWorth() *NetWorthSummary {
	if x != nil {
		return x.NetWorth
	}
	return nil
}

func (x *FinancialSummary) GetTopExpenseCategories() []*CategorySummary {
	if x != nil {
		return x.TopExpenseCategories
	}
	return nil
}

func (x *FinancialSummary) GetTopIncomeCategories() []*CategorySummary {
	if x != nil {
		return x.TopIncomeCategories
	}
	return nil
}

func (x *FinancialSummary) GetWalletSummaries() []*WalletSummary {
	if x != nil {
		return x.WalletSummaries
	}
	return nil
}

type GetUserFinancialSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*FinancialSummary    `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFinancialSummaryResponse) Reset() {
	*x = GetUserFinancialSummaryResponse{}
	mi := &file_dashboard_dashboard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFinancialSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFinancialSummaryResponse) ProtoMessage() {}

func (x *GetUserFinancialSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFinancialSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUserFinancialSummaryResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserFinancialSummaryResponse) GetSummaries() []*FinancialSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type GetUserNetWorthCompositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNetWorthCompositionRequest) Reset() {
	*x = GetUserNetWorthCompositionRequest{}
	mi := &file_dashboard_dashboard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNetWorthCompositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNetWorthCompositionRequest) ProtoMessage() {}

func (x *GetUserNetWorthCompositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNetWorthCompositionRequest.ProtoReflect.Descriptor instead.
func (*GetUserNetWorthCompositionRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserNetWorthCompositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NetWorthSliceDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemCount      int32                  `protobuf:"varint,1,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UnrealizedGain float64                `protobuf:"fixed64,3,opt,name=unrealized_gain,json=unrealizedGain,proto3" json:"unrealized_gain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetWorthSliceDetails) Reset() {
	*x = NetWorthSliceDetails{}
	mi := &file_dashboard_dashboard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthSliceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthSliceDetails) ProtoMessage() {}

func (x *NetWorthSliceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthSliceDetails.ProtoReflect.Descriptor instead.
func (*NetWorthSliceDetails) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{20}
}

func (x *NetWorthSliceDetails) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *NetWorthSliceDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NetWorthSliceDetails) GetUnrealizedGain() float64 {
	if x != nil {
		return x.UnrealizedGain
	}
	return 0
}

type NetWorthSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Details       *NetWorthSliceDetails  `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetWorthSlice) Reset() {
	*x = NetWorthSlice{}
	mi := &file_dashboard_dashboard_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthSlice) ProtoMessage() {}

func (x *NetWorthSlice) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthSlice.ProtoReflect.Descriptor instead.
func (*NetWorthSlice) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{21}
}

func (x *NetWorthSlice) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NetWorthSlice) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NetWorthSlice) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *NetWorthSlice) GetDetails() *NetWorthSliceDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type NetWorthComposition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Slices        []*NetWorthSlice       `protobuf:"bytes,3,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetWorthComposition) Reset() {
	*x = NetWorthComposition{}
	mi := &file_dashboard_dashboard_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthComposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthComposition) ProtoMessage() {}

func (x *NetWorthComposition) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthComposition.ProtoReflect.Descriptor instead.
func (*NetWorthComposition) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{22}
}

func (x *NetWorthComposition) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NetWorthComposition) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NetWorthComposition) GetSlices() []*NetWorthSlice {
	if x != nil {
		return x.Slices
	}
	return nil
}

type DashboardWallet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletName     string                 `protobuf:"bytes,3,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	WalletType     string                 `protobuf:"bytes,4,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	WalletTypeName string                 `protobuf:"bytes,5,opt,name=wallet_type_name,json=walletTypeName,proto3" json:"wallet_type_name,omitempty"`
	Balance        float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency       string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Icon           string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	IsActive       bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardWallet) Reset() {
	*x = DashboardWallet{}
	mi := &file_dashboard_dashboard_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardWallet) ProtoMessage() {}

func (x *DashboardWallet) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardWallet.ProtoReflect.Descriptor instead.
func (*DashboardWallet) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{23}
}

func (x *DashboardWallet) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DashboardWallet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DashboardWallet) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *DashboardWallet) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *DashboardWallet) GetWalletTypeName() string {
	if x != nil {
		return x.WalletTypeName
	}
	return ""
}

func (x *DashboardWallet) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *DashboardWallet) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DashboardWallet) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *DashboardWallet) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetUserWalletsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*DashboardWallet     `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWalletsResponse) Reset() {
	*x = GetUserWalletsResponse{}
	mi := &file_dashboard_dashboard_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWalletsResponse) ProtoMessage() {}

func (x *GetUserWalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_dashboard_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWalletsResponse.ProtoReflect.Descriptor instead.
func (*GetUserWalletsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_dashboard_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserWalletsResponse) GetWallets() []*DashboardWallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

var File_dashboard_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x19dashboard/dashboard.proto\x12\tdashboard\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\tDateRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\x88\x01\n" +
	"\n" +
	"DateOption\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x04 \x01(\x05R\x03day\x12*\n" +
	"\x05range\x18\x05 \x01(\v2\x14.dashboard.DateRangeR\x05range\"\x8a\x01\n" +
	"\x1aGetUserTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x126\n" +
	"\vdate_option\x18\x03 \x01(\v2\x15.dashboard.DateOptionR\n" +
	"dateOption\"\x84\x02\n" +
	"\x13TransactionCategory\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12#\n" +
	"\rcategory_type\x18\x03 \x01(\tR\fcategoryType\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12-\n" +
	"\x12total_transactions\x18\x05 \x01(\x05R\x11totalTransactions\x120\n" +
	"\x14parent_category_name\x18\x06 \x01(\tR\x12parentCategoryName\"]\n" +
	"\x1bGetUserTransactionsResponse\x12>\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1e.dashboard.TransactionCategoryR\n" +
	"categories\"\xaf\x01\n" +
	"\x1eGetCategoryTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x126\n" +
	"\vdate_option\x18\x04 \x01(\v2\x15.dashboard.DateOptionR\n" +
	"dateOption\"\xc6\x01\n" +
	"\x17CategoryTransactionItem\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10transaction_date\x18\x03 \x01(\tR\x0ftransactionDate\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vwallet_name\x18\x05 \x01(\tR\n" +
	"walletName\"\x86\x02\n" +
	"\x1fGetCategoryTransactionsResponse\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12#\n" +
	"\rcategory_type\x18\x03 \x01(\tR\fcategoryType\x120\n" +
	"\x14parent_category_name\x18\x04 \x01(\tR\x12parentCategoryName\x12F\n" +
	"\ftransactions\x18\x05 \x03(\v2\".dashboard.CategoryTransactionItemR\ftransactions\"\x9b\x01\n" +
	"\x15GetUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12 \n" +
	"\vaggregation\x18\x03 \x01(\tR\vaggregation\x12*\n" +
	"\x05range\x18\x04 \x01(\v2\x14.dashboard.DateRangeR\x05range\"\x99\x03\n" +
	"\x0fBalanceSnapshot\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vwallet_name\x18\x02 \x01(\tR\n" +
	"walletName\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x05 \x01(\x05R\x05month\x12\x12\n" +
	"\x04week\x18\x06 \x01(\x05R\x04week\x12\x10\n" +
	"\x03day\x18\a \x01(\x05R\x03day\x12'\n" +
	"\x0fopening_balance\x18\b \x01(\x01R\x0eopeningBalance\x12'\n" +
	"\x0fclosing_balance\x18\t \x01(\x01R\x0eclosingBalance\x12!\n" +
	"\ftotal_income\x18\n" +
	" \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\v \x01(\x01R\ftotalExpense\x12\x1d\n" +
	"\n" +
	"net_change\x18\f \x01(\x01R\tnetChange\x12+\n" +
	"\x11transaction_count\x18\r \x01(\x05R\x10transactionCount\"R\n" +
	"\x16GetUserBalanceResponse\x128\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1a.dashboard.BalanceSnapshotR\tsnapshots\"\x82\x01\n" +
	"\x1eGetUserFinancialSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12*\n" +
	"\x05range\x18\x03 \x01(\v2\x14.dashboard.DateRangeR\x05range\"\xbc\x01\n" +
	"\x0fCategorySummary\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\x12+\n" +
	"\x11transaction_count\x18\x05 \x01(\x05R\x10transactionCount\"\xc2\x02\n" +
	"\rWalletSummary\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vwallet_name\x18\x02 \x01(\tR\n" +
	"walletName\x12\x1f\n" +
	"\vwallet_type\x18\x03 \x01(\tR\n" +
	"walletType\x12'\n" +
	"\x0fopening_balance\x18\x04 \x01(\x01R\x0eopeningBalance\x12'\n" +
	"\x0fclosing_balance\x18\x05 \x01(\x01R\x0eclosingBalance\x12\x16\n" +
	"\x06income\x18\x06 \x01(\x01R\x06income\x12\x18\n" +
	"\aexpense\x18\a \x01(\x01R\aexpense\x12\x1d\n" +
	"\n" +
	"net_change\x18\b \x01(\x01R\tnetChange\x12/\n" +
	"\x14share_of_balance_pct\x18\t \x01(\x01R\x11shareOfBalancePct\"\xac\x03\n" +
	"\x11InvestmentSummary\x12%\n" +
	"\x0etotal_invested\x18\x01 \x01(\x01R\rtotalInvested\x126\n" +
	"\x17total_current_valuation\x18\x02 \x01(\x01R\x15totalCurrentValuation\x12*\n" +
	"\x11total_sold_amount\x18\x03 \x01(\x01R\x0ftotalSoldAmount\x12#\n" +
	"\rtotal_deficit\x18\x04 \x01(\x01R\ftotalDeficit\x12'\n" +
	"\x0funrealized_gain\x18\x05 \x01(\x01R\x0eunrealizedGain\x12#\n" +
	"\rrealized_gain\x18\x06 \x01(\x01R\frealizedGain\x122\n" +
	"\x15investment_growth_pct\x18\a \x01(\x01R\x13investmentGrowthPct\x12\x1b\n" +
	"\tbuy_count\x18\b \x01(\x05R\bbuyCount\x12\x1d\n" +
	"\n" +
	"sell_count\x18\t \x01(\x05R\tsellCount\x12)\n" +
	"\x10active_positions\x18\n" +
	" \x01(\x05R\x0factivePositions\"\xd4\x01\n" +
	"\x0fNetWorthSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12%\n" +
	"\x0ewallet_portion\x18\x02 \x01(\x01R\rwalletPortion\x12-\n" +
	"\x12investment_portion\x18\x03 \x01(\x01R\x11investmentPortion\x12$\n" +
	"\x0enet_worth_prev\x18\x04 \x01(\x01R\fnetWorthPrev\x12/\n" +
	"\x14net_worth_growth_pct\x18\x05 \x01(\x01R\x11netWorthGrowthPct\"\xfa\v\n" +
	"\x10FinancialSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vperiod_type\x18\x02 \x01(\tR\n" +
	"periodType\x12\x1d\n" +
	"\n" +
	"period_key\x18\x03 \x01(\tR\tperiodKey\x12!\n" +
	"\fperiod_start\x18\x04 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x05 \x01(\tR\tperiodEnd\x12\x1d\n" +
	"\n" +
	"income_now\x18\x06 \x01(\x01R\tincomeNow\x12\x1f\n" +
	"\vexpense_now\x18\a \x01(\x01R\n" +
	"expenseNow\x12\x1d\n" +
	"\n" +
	"profit_now\x18\b \x01(\x01R\tprofitNow\x12\x1f\n" +
	"\vbalance_now\x18\t \x01(\x01R\n" +
	"balanceNow\x12\x1f\n" +
	"\vincome_prev\x18\n" +
	" \x01(\x01R\n" +
	"incomePrev\x12!\n" +
	"\fexpense_prev\x18\v \x01(\x01R\vexpensePrev\x12\x1f\n" +
	"\vprofit_prev\x18\f \x01(\x01R\n" +
	"profitPrev\x12!\n" +
	"\fbalance_prev\x18\r \x01(\x01R\vbalancePrev\x12*\n" +
	"\x11income_growth_pct\x18\x0e \x01(\x01R\x0fincomeGrowthPct\x12,\n" +
	"\x12expense_growth_pct\x18\x0f \x01(\x01R\x10expenseGrowthPct\x12*\n" +
	"\x11profit_growth_pct\x18\x10 \x01(\x01R\x0fprofitGrowthPct\x12,\n" +
	"\x12balance_growth_pct\x18\x11 \x01(\x01R\x10balanceGrowthPct\x12!\n" +
	"\fsavings_rate\x18\x12 \x01(\x01R\vsavingsRate\x125\n" +
	"\x17expense_to_income_ratio\x18\x13 \x01(\x01R\x14expenseToIncomeRatio\x12&\n" +
	"\x0fburn_rate_daily\x18\x14 \x01(\x01R\rburnRateDaily\x12(\n" +
	"\x10avg_income_daily\x18\x15 \x01(\x01R\x0eavgIncomeDaily\x12*\n" +
	"\x11avg_expense_daily\x18\x16 \x01(\x01R\x0favgExpenseDaily\x12\x1f\n" +
	"\vrunway_days\x18\x17 \x01(\x01R\n" +
	"runwayDays\x12-\n" +
	"\x12total_transactions\x18\x18 \x01(\x05R\x11totalTransactions\x128\n" +
	"\x18income_transaction_count\x18\x19 \x01(\x05R\x16incomeTransactionCount\x12:\n" +
	"\x19expense_transaction_count\x18\x1a \x01(\x05R\x17expenseTransactionCount\x124\n" +
	"\x16avg_transaction_amount\x18\x1b \x01(\x01R\x14avgTransactionAmount\x12%\n" +
	"\x0elargest_income\x18\x1c \x01(\x01R\rlargestIncome\x12'\n" +
	"\x0flargest_expense\x18\x1d \x01(\x01R\x0elargestExpense\x12K\n" +
	"\x12investment_summary\x18\x1e \x01(\v2\x1c.dashboard.InvestmentSummaryR\x11investmentSummary\x127\n" +
	"\tnet_worth\x18\x1f \x01(\v2\x1a.dashboard.NetWorthSummaryR\bnetWorth\x12P\n" +
	"\x16top_expense_categories\x18  \x03(\v2\x1a.dashboard.CategorySummaryR\x14topExpenseCategories\x12N\n" +
	"\x15top_income_categories\x18! \x03(\v2\x1a.dashboard.CategorySummaryR\x13topIncomeCategories\x12C\n" +
	"\x10wallet_summaries\x18\" \x03(\v2\x18.dashboard.WalletSummaryR\x0fwalletSummaries\"\\\n" +
	"\x1fGetUserFinancialSummaryResponse\x129\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1b.dashboard.FinancialSummaryR\tsummaries\"<\n" +
	"!GetUserNetWorthCompositionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x80\x01\n" +
	"\x14NetWorthSliceDetails\x12\x1d\n" +
	"\n" +
	"item_count\x18\x01 \x01(\x05R\titemCount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0funrealized_gain\x18\x03 \x01(\x01R\x0eunrealizedGain\"\x98\x01\n" +
	"\rNetWorthSlice\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x129\n" +
	"\adetails\x18\x04 \x01(\v2\x1f.dashboard.NetWorthSliceDetailsR\adetails\"v\n" +
	"\x13NetWorthComposition\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x120\n" +
	"\x06slices\x18\x03 \x03(\v2\x18.dashboard.NetWorthSliceR\x06slices\"\x9a\x02\n" +
	"\x0fDashboardWallet\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vwallet_name\x18\x03 \x01(\tR\n" +
	"walletName\x12\x1f\n" +
	"\vwallet_type\x18\x04 \x01(\tR\n" +
	"walletType\x12(\n" +
	"\x10wallet_type_name\x18\x05 \x01(\tR\x0ewalletTypeName\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"N\n" +
	"\x16GetUserWalletsResponse\x124\n" +
	"\awallets\x18\x01 \x03(\v2\x1a.dashboard.DashboardWalletR\awallets2\xe7\x04\n" +
	"\x10DashboardService\x12d\n" +
	"\x13GetUserTransactions\x12%.dashboard.GetUserTransactionsRequest\x1a&.dashboard.GetUserTransactionsResponse\x12p\n" +
	"\x17GetCategoryTransactions\x12).dashboard.GetCategoryTransactionsRequest\x1a*.dashboard.GetCategoryTransactionsResponse\x12U\n" +
	"\x0eGetUserBalance\x12 .dashboard.GetUserBalanceRequest\x1a!.dashboard.GetUserBalanceResponse\x12p\n" +
	"\x17GetUserFinancialSummary\x12).dashboard.GetUserFinancialSummaryRequest\x1a*.dashboard.GetUserFinancialSummaryResponse\x12j\n" +
	"\x1aGetUserNetWorthComposition\x12,.dashboard.GetUserNetWorthCompositionRequest\x1a\x1e.dashboard.NetWorthComposition\x12F\n" +
	"\x0eGetUserWallets\x12\x11.dashboard.UserID\x1a!.dashboard.GetUserWalletsResponseB5Z3github.com/MuhammadMiftaa/Refina-Protobuf/dashboardb\x06proto3"

var (
	file_dashboard_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_dashboard_proto_rawDescData []byte
)

func file_dashboard_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_dashboard_proto_rawDesc), len(file_dashboard_dashboard_proto_rawDesc)))
	})
	return file_dashboard_dashboard_proto_rawDescData
}

var file_dashboard_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_dashboard_dashboard_proto_goTypes = []any{
	(*UserID)(nil),                            // 0: dashboard.UserID
	(*DateRange)(nil),                         // 1: dashboard.DateRange
	(*DateOption)(nil),                        // 2: dashboard.DateOption
	(*GetUserTransactionsRequest)(nil),        // 3: dashboard.GetUserTransactionsRequest
	(*TransactionCategory)(nil),               // 4: dashboard.TransactionCategory
	(*GetUserTransactionsResponse)(nil),       // 5: dashboard.GetUserTransactionsResponse
	(*GetCategoryTransactionsRequest)(nil),    // 6: dashboard.GetCategoryTransactionsRequest
	(*CategoryTransactionItem)(nil),           // 7: dashboard.CategoryTransactionItem
	(*GetCategoryTransactionsResponse)(nil),   // 8: dashboard.GetCategoryTransactionsResponse
	(*GetUserBalanceRequest)(nil),             // 9: dashboard.GetUserBalanceRequest
	(*BalanceSnapshot)(nil),                   // 10: dashboard.BalanceSnapshot
	(*GetUserBalanceResponse)(nil),            // 11: dashboard.GetUserBalanceResponse
	(*GetUserFinancialSummaryRequest)(nil),    // 12: dashboard.GetUserFinancialSummaryRequest
	(*CategorySummary)(nil),                   // 13: dashboard.CategorySummary
	(*WalletSummary)(nil),                     // 14: dashboard.WalletSummary
	(*InvestmentSummary)(nil),                 // 15: dashboard.InvestmentSummary
	(*NetWorthSummary)(nil),                   // 16: dashboard.NetWorthSummary
	(*FinancialSummary)(nil),                  // 17: dashboard.FinancialSummary
	(*GetUserFinancialSummaryResponse)(nil),   // 18: dashboard.GetUserFinancialSummaryResponse
	(*GetUserNetWorthCompositionRequest)(nil), // 19: dashboard.GetUserNetWorthCompositionRequest
	(*NetWorthSliceDetails)(nil),              // 20: dashboard.NetWorthSliceDetails
	(*NetWorthSlice)(nil),                     // 21: dashboard.NetWorthSlice
	(*NetWorthComposition)(nil),               // 22: dashboard.NetWorthComposition
	(*DashboardWallet)(nil),                   // 23: dashboard.DashboardWallet
	(*GetUserWalletsResponse)(nil),            // 24: dashboard.GetUserWalletsResponse
}
var file_dashboard_dashboard_proto_depIdxs = []int32{
	1,  // 0: dashboard.DateOption.range:type_name -> dashboard.DateRange
	2,  // 1: dashboard.GetUserTransactionsRequest.date_option:type_name -> dashboard.DateOption
	4,  // 2: dashboard.GetUserTransactionsResponse.categories:type_name -> dashboard.TransactionCategory
	2,  // 3: dashboard.GetCategoryTransactionsRequest.date_option:type_name -> dashboard.DateOption
	7,  // 4: dashboard.GetCategoryTransactionsResponse.transactions:type_name -> dashboard.CategoryTransactionItem
	1,  // 5: dashboard.GetUserBalanceRequest.range:type_name -> dashboard.DateRange
	10, // 6: dashboard.GetUserBalanceResponse.snapshots:type_name -> dashboard.BalanceSnapshot
	1,  // 7: dashboard.GetUserFinancialSummaryRequest.range:type_name -> dashboard.DateRange
	15, // 8: dashboard.FinancialSummary.investment_summary:type_name -> dashboard.InvestmentSummary
	16, // 9: dashboard.FinancialSummary.net_worth:type_name -> dashboard.NetWorthSummary
	13, // 10: dashboard.FinancialSummary.top_expense_categories:type_name -> dashboard.CategorySummary
	13, // 11: dashboard.FinancialSummary.top_income_categories:type_name -> dashboard.CategorySummary
	14, // 12: dashboard.FinancialSummary.wallet_summaries:type_name -> dashboard.WalletSummary
	17, // 13: dashboard.GetUserFinancialSummaryResponse.summaries:type_name -> dashboard.FinancialSummary
	20, // 14: dashboard.NetWorthSlice.details:type_name -> dashboard.NetWorthSliceDetails
	21, // 15: dashboard.NetWorthComposition.slices:type_name -> dashboard.NetWorthSlice
	23, // 16: dashboard.GetUserWalletsResponse.wallets:type_name -> dashboard.DashboardWallet
	3,  // 17: dashboard.DashboardService.GetUserTransactions:input_type -> dashboard.GetUserTransactionsRequest
	6,  // 18: dashboard.DashboardService.GetCategoryTransactions:input_type -> dashboard.GetCategoryTransactionsRequest
	9,  // 19: dashboard.DashboardService.GetUserBalance:input_type -> dashboard.GetUserBalanceRequest
	12, // 20: dashboard.DashboardService.GetUserFinancialSummary:input_type -> dashboard.GetUserFinancialSummaryRequest
	19, // 21: dashboard.DashboardService.GetUserNetWorthComposition:input_type -> dashboard.GetUserNetWorthCompositionRequest
	0,  // 22: dashboard.DashboardService.GetUserWallets:input_type -> dashboard.UserID
	5,  // 23: dashboard.DashboardService.GetUserTransactions:output_type -> dashboard.GetUserTransactionsResponse
	8,  // 24: dashboard.DashboardService.GetCategoryTransactions:output_type -> dashboard.GetCategoryTransactionsResponse
	11, // 25: dashboard.DashboardService.GetUserBalance:output_type -> dashboard.GetUserBalanceResponse
	18, // 26: dashboard.DashboardService.GetUserFinancialSummary:output_type -> dashboard.GetUserFinancialSummaryResponse
	22, // 27: dashboard.DashboardService.GetUserNetWorthComposition:output_type -> dashboard.NetWorthComposition
	24, // 28: dashboard.DashboardService.GetUserWallets:output_type -> dashboard.GetUserWalletsResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_dashboard_dashboard_proto_init() }
func file_dashboard_dashboard_proto_init() {
	if File_dashboard_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_dashboard_proto_rawDesc), len(file_dashboard_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_dashboard_proto = out.File
	file_dashboard_dashboard_proto_goTypes = nil
	file_dashboard_dashboard_proto_depIdxs = nil
}
