<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.DashboardWallet</code>
 */
class DashboardWallet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string wallet_id = 1;</code>
     */
    protected $wallet_id = '';
    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string wallet_name = 3;</code>
     */
    protected $wallet_name = '';
    /**
     * Generated from protobuf field <code>string wallet_type = 4;</code>
     */
    protected $wallet_type = '';
    /**
     * Generated from protobuf field <code>string wallet_type_name = 5;</code>
     */
    protected $wallet_type_name = '';
    /**
     * Generated from protobuf field <code>double balance = 6;</code>
     */
    protected $balance = 0.0;
    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string icon = 8;</code>
     */
    protected $icon = '';
    /**
     * Generated from protobuf field <code>bool is_active = 9;</code>
     */
    protected $is_active = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $wallet_id
     *     @type string $user_id
     *     @type string $wallet_name
     *     @type string $wallet_type
     *     @type string $wallet_type_name
     *     @type float $balance
     *     @type string $currency
     *     @type string $icon
     *     @type bool $is_active
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 1;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_name = 3;</code>
     * @return string
     */
    public function getWalletName()
    {
        return $this->wallet_name;
    }

    /**
     * Generated from protobuf field <code>string wallet_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletName($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_type = 4;</code>
     * @return string
     */
    public function getWalletType()
    {
        return $this->wallet_type;
    }

    /**
     * Generated from protobuf field <code>string wallet_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletType($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_type_name = 5;</code>
     * @return string
     */
    public function getWalletTypeName()
    {
        return $this->wallet_type_name;
    }

    /**
     * Generated from protobuf field <code>string wallet_type_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_type_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double balance = 6;</code>
     * @return float
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>double balance = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon = 8;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     * Generated from protobuf field <code>string icon = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 9;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return $this->is_active;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->is_active = $var;

        return $this;
    }

}

