<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.FinancialSummary</code>
 */
class FinancialSummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string period_type = 2;</code>
     */
    protected $period_type = '';
    /**
     * Generated from protobuf field <code>string period_key = 3;</code>
     */
    protected $period_key = '';
    /**
     * Generated from protobuf field <code>string period_start = 4;</code>
     */
    protected $period_start = '';
    /**
     * Generated from protobuf field <code>string period_end = 5;</code>
     */
    protected $period_end = '';
    /**
     * Current period values
     *
     * Generated from protobuf field <code>double income_now = 6;</code>
     */
    protected $income_now = 0.0;
    /**
     * Generated from protobuf field <code>double expense_now = 7;</code>
     */
    protected $expense_now = 0.0;
    /**
     * Generated from protobuf field <code>double profit_now = 8;</code>
     */
    protected $profit_now = 0.0;
    /**
     * Generated from protobuf field <code>double balance_now = 9;</code>
     */
    protected $balance_now = 0.0;
    /**
     * Previous period values
     *
     * Generated from protobuf field <code>double income_prev = 10;</code>
     */
    protected $income_prev = 0.0;
    /**
     * Generated from protobuf field <code>double expense_prev = 11;</code>
     */
    protected $expense_prev = 0.0;
    /**
     * Generated from protobuf field <code>double profit_prev = 12;</code>
     */
    protected $profit_prev = 0.0;
    /**
     * Generated from protobuf field <code>double balance_prev = 13;</code>
     */
    protected $balance_prev = 0.0;
    /**
     * Growth percentages
     *
     * Generated from protobuf field <code>double income_growth_pct = 14;</code>
     */
    protected $income_growth_pct = 0.0;
    /**
     * Generated from protobuf field <code>double expense_growth_pct = 15;</code>
     */
    protected $expense_growth_pct = 0.0;
    /**
     * Generated from protobuf field <code>double profit_growth_pct = 16;</code>
     */
    protected $profit_growth_pct = 0.0;
    /**
     * Generated from protobuf field <code>double balance_growth_pct = 17;</code>
     */
    protected $balance_growth_pct = 0.0;
    /**
     * Ratios & health indicators
     *
     * Generated from protobuf field <code>double savings_rate = 18;</code>
     */
    protected $savings_rate = 0.0;
    /**
     * Generated from protobuf field <code>double expense_to_income_ratio = 19;</code>
     */
    protected $expense_to_income_ratio = 0.0;
    /**
     * Generated from protobuf field <code>double burn_rate_daily = 20;</code>
     */
    protected $burn_rate_daily = 0.0;
    /**
     * Generated from protobuf field <code>double avg_income_daily = 21;</code>
     */
    protected $avg_income_daily = 0.0;
    /**
     * Generated from protobuf field <code>double avg_expense_daily = 22;</code>
     */
    protected $avg_expense_daily = 0.0;
    /**
     * Generated from protobuf field <code>double runway_days = 23;</code>
     */
    protected $runway_days = 0.0;
    /**
     * Transaction stats
     *
     * Generated from protobuf field <code>int32 total_transactions = 24;</code>
     */
    protected $total_transactions = 0;
    /**
     * Generated from protobuf field <code>int32 income_transaction_count = 25;</code>
     */
    protected $income_transaction_count = 0;
    /**
     * Generated from protobuf field <code>int32 expense_transaction_count = 26;</code>
     */
    protected $expense_transaction_count = 0;
    /**
     * Generated from protobuf field <code>double avg_transaction_amount = 27;</code>
     */
    protected $avg_transaction_amount = 0.0;
    /**
     * Generated from protobuf field <code>double largest_income = 28;</code>
     */
    protected $largest_income = 0.0;
    /**
     * Generated from protobuf field <code>double largest_expense = 29;</code>
     */
    protected $largest_expense = 0.0;
    /**
     * Nested summaries
     *
     * Generated from protobuf field <code>.dashboard.InvestmentSummary investment_summary = 30;</code>
     */
    protected $investment_summary = null;
    /**
     * Generated from protobuf field <code>.dashboard.NetWorthSummary net_worth = 31;</code>
     */
    protected $net_worth = null;
    /**
     * Top categories
     *
     * Generated from protobuf field <code>repeated .dashboard.CategorySummary top_expense_categories = 32;</code>
     */
    private $top_expense_categories;
    /**
     * Generated from protobuf field <code>repeated .dashboard.CategorySummary top_income_categories = 33;</code>
     */
    private $top_income_categories;
    /**
     * Per wallet breakdown
     *
     * Generated from protobuf field <code>repeated .dashboard.WalletSummary wallet_summaries = 34;</code>
     */
    private $wallet_summaries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $period_type
     *     @type string $period_key
     *     @type string $period_start
     *     @type string $period_end
     *     @type float $income_now
     *           Current period values
     *     @type float $expense_now
     *     @type float $profit_now
     *     @type float $balance_now
     *     @type float $income_prev
     *           Previous period values
     *     @type float $expense_prev
     *     @type float $profit_prev
     *     @type float $balance_prev
     *     @type float $income_growth_pct
     *           Growth percentages
     *     @type float $expense_growth_pct
     *     @type float $profit_growth_pct
     *     @type float $balance_growth_pct
     *     @type float $savings_rate
     *           Ratios & health indicators
     *     @type float $expense_to_income_ratio
     *     @type float $burn_rate_daily
     *     @type float $avg_income_daily
     *     @type float $avg_expense_daily
     *     @type float $runway_days
     *     @type int $total_transactions
     *           Transaction stats
     *     @type int $income_transaction_count
     *     @type int $expense_transaction_count
     *     @type float $avg_transaction_amount
     *     @type float $largest_income
     *     @type float $largest_expense
     *     @type \Dashboard\InvestmentSummary $investment_summary
     *           Nested summaries
     *     @type \Dashboard\NetWorthSummary $net_worth
     *     @type array<\Dashboard\CategorySummary>|\Google\Protobuf\Internal\RepeatedField $top_expense_categories
     *           Top categories
     *     @type array<\Dashboard\CategorySummary>|\Google\Protobuf\Internal\RepeatedField $top_income_categories
     *     @type array<\Dashboard\WalletSummary>|\Google\Protobuf\Internal\RepeatedField $wallet_summaries
     *           Per wallet breakdown
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period_type = 2;</code>
     * @return string
     */
    public function getPeriodType()
    {
        return $this->period_type;
    }

    /**
     * Generated from protobuf field <code>string period_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriodType($var)
    {
        GPBUtil::checkString($var, True);
        $this->period_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period_key = 3;</code>
     * @return string
     */
    public function getPeriodKey()
    {
        return $this->period_key;
    }

    /**
     * Generated from protobuf field <code>string period_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriodKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->period_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period_start = 4;</code>
     * @return string
     */
    public function getPeriodStart()
    {
        return $this->period_start;
    }

    /**
     * Generated from protobuf field <code>string period_start = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriodStart($var)
    {
        GPBUtil::checkString($var, True);
        $this->period_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period_end = 5;</code>
     * @return string
     */
    public function getPeriodEnd()
    {
        return $this->period_end;
    }

    /**
     * Generated from protobuf field <code>string period_end = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriodEnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->period_end = $var;

        return $this;
    }

    /**
     * Current period values
     *
     * Generated from protobuf field <code>double income_now = 6;</code>
     * @return float
     */
    public function getIncomeNow()
    {
        return $this->income_now;
    }

    /**
     * Current period values
     *
     * Generated from protobuf field <code>double income_now = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setIncomeNow($var)
    {
        GPBUtil::checkDouble($var);
        $this->income_now = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double expense_now = 7;</code>
     * @return float
     */
    public function getExpenseNow()
    {
        return $this->expense_now;
    }

    /**
     * Generated from protobuf field <code>double expense_now = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setExpenseNow($var)
    {
        GPBUtil::checkDouble($var);
        $this->expense_now = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double profit_now = 8;</code>
     * @return float
     */
    public function getProfitNow()
    {
        return $this->profit_now;
    }

    /**
     * Generated from protobuf field <code>double profit_now = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setProfitNow($var)
    {
        GPBUtil::checkDouble($var);
        $this->profit_now = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double balance_now = 9;</code>
     * @return float
     */
    public function getBalanceNow()
    {
        return $this->balance_now;
    }

    /**
     * Generated from protobuf field <code>double balance_now = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setBalanceNow($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance_now = $var;

        return $this;
    }

    /**
     * Previous period values
     *
     * Generated from protobuf field <code>double income_prev = 10;</code>
     * @return float
     */
    public function getIncomePrev()
    {
        return $this->income_prev;
    }

    /**
     * Previous period values
     *
     * Generated from protobuf field <code>double income_prev = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setIncomePrev($var)
    {
        GPBUtil::checkDouble($var);
        $this->income_prev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double expense_prev = 11;</code>
     * @return float
     */
    public function getExpensePrev()
    {
        return $this->expense_prev;
    }

    /**
     * Generated from protobuf field <code>double expense_prev = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setExpensePrev($var)
    {
        GPBUtil::checkDouble($var);
        $this->expense_prev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double profit_prev = 12;</code>
     * @return float
     */
    public function getProfitPrev()
    {
        return $this->profit_prev;
    }

    /**
     * Generated from protobuf field <code>double profit_prev = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setProfitPrev($var)
    {
        GPBUtil::checkDouble($var);
        $this->profit_prev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double balance_prev = 13;</code>
     * @return float
     */
    public function getBalancePrev()
    {
        return $this->balance_prev;
    }

    /**
     * Generated from protobuf field <code>double balance_prev = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setBalancePrev($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance_prev = $var;

        return $this;
    }

    /**
     * Growth percentages
     *
     * Generated from protobuf field <code>double income_growth_pct = 14;</code>
     * @return float
     */
    public function getIncomeGrowthPct()
    {
        return $this->income_growth_pct;
    }

    /**
     * Growth percentages
     *
     * Generated from protobuf field <code>double income_growth_pct = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setIncomeGrowthPct($var)
    {
        GPBUtil::checkDouble($var);
        $this->income_growth_pct = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double expense_growth_pct = 15;</code>
     * @return float
     */
    public function getExpenseGrowthPct()
    {
        return $this->expense_growth_pct;
    }

    /**
     * Generated from protobuf field <code>double expense_growth_pct = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setExpenseGrowthPct($var)
    {
        GPBUtil::checkDouble($var);
        $this->expense_growth_pct = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double profit_growth_pct = 16;</code>
     * @return float
     */
    public function getProfitGrowthPct()
    {
        return $this->profit_growth_pct;
    }

    /**
     * Generated from protobuf field <code>double profit_growth_pct = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setProfitGrowthPct($var)
    {
        GPBUtil::checkDouble($var);
        $this->profit_growth_pct = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double balance_growth_pct = 17;</code>
     * @return float
     */
    public function getBalanceGrowthPct()
    {
        return $this->balance_growth_pct;
    }

    /**
     * Generated from protobuf field <code>double balance_growth_pct = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setBalanceGrowthPct($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance_growth_pct = $var;

        return $this;
    }

    /**
     * Ratios & health indicators
     *
     * Generated from protobuf field <code>double savings_rate = 18;</code>
     * @return float
     */
    public function getSavingsRate()
    {
        return $this->savings_rate;
    }

    /**
     * Ratios & health indicators
     *
     * Generated from protobuf field <code>double savings_rate = 18;</code>
     * @param float $var
     * @return $this
     */
    public function setSavingsRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->savings_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double expense_to_income_ratio = 19;</code>
     * @return float
     */
    public function getExpenseToIncomeRatio()
    {
        return $this->expense_to_income_ratio;
    }

    /**
     * Generated from protobuf field <code>double expense_to_income_ratio = 19;</code>
     * @param float $var
     * @return $this
     */
    public function setExpenseToIncomeRatio($var)
    {
        GPBUtil::checkDouble($var);
        $this->expense_to_income_ratio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double burn_rate_daily = 20;</code>
     * @return float
     */
    public function getBurnRateDaily()
    {
        return $this->burn_rate_daily;
    }

    /**
     * Generated from protobuf field <code>double burn_rate_daily = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setBurnRateDaily($var)
    {
        GPBUtil::checkDouble($var);
        $this->burn_rate_daily = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avg_income_daily = 21;</code>
     * @return float
     */
    public function getAvgIncomeDaily()
    {
        return $this->avg_income_daily;
    }

    /**
     * Generated from protobuf field <code>double avg_income_daily = 21;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgIncomeDaily($var)
    {
        GPBUtil::checkDouble($var);
        $this->avg_income_daily = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avg_expense_daily = 22;</code>
     * @return float
     */
    public function getAvgExpenseDaily()
    {
        return $this->avg_expense_daily;
    }

    /**
     * Generated from protobuf field <code>double avg_expense_daily = 22;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgExpenseDaily($var)
    {
        GPBUtil::checkDouble($var);
        $this->avg_expense_daily = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double runway_days = 23;</code>
     * @return float
     */
    public function getRunwayDays()
    {
        return $this->runway_days;
    }

    /**
     * Generated from protobuf field <code>double runway_days = 23;</code>
     * @param float $var
     * @return $this
     */
    public function setRunwayDays($var)
    {
        GPBUtil::checkDouble($var);
        $this->runway_days = $var;

        return $this;
    }

    /**
     * Transaction stats
     *
     * Generated from protobuf field <code>int32 total_transactions = 24;</code>
     * @return int
     */
    public function getTotalTransactions()
    {
        return $this->total_transactions;
    }

    /**
     * Transaction stats
     *
     * Generated from protobuf field <code>int32 total_transactions = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalTransactions($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_transactions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 income_transaction_count = 25;</code>
     * @return int
     */
    public function getIncomeTransactionCount()
    {
        return $this->income_transaction_count;
    }

    /**
     * Generated from protobuf field <code>int32 income_transaction_count = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setIncomeTransactionCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->income_transaction_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expense_transaction_count = 26;</code>
     * @return int
     */
    public function getExpenseTransactionCount()
    {
        return $this->expense_transaction_count;
    }

    /**
     * Generated from protobuf field <code>int32 expense_transaction_count = 26;</code>
     * @param int $var
     * @return $this
     */
    public function setExpenseTransactionCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->expense_transaction_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double avg_transaction_amount = 27;</code>
     * @return float
     */
    public function getAvgTransactionAmount()
    {
        return $this->avg_transaction_amount;
    }

    /**
     * Generated from protobuf field <code>double avg_transaction_amount = 27;</code>
     * @param float $var
     * @return $this
     */
    public function setAvgTransactionAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->avg_transaction_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double largest_income = 28;</code>
     * @return float
     */
    public function getLargestIncome()
    {
        return $this->largest_income;
    }

    /**
     * Generated from protobuf field <code>double largest_income = 28;</code>
     * @param float $var
     * @return $this
     */
    public function setLargestIncome($var)
    {
        GPBUtil::checkDouble($var);
        $this->largest_income = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double largest_expense = 29;</code>
     * @return float
     */
    public function getLargestExpense()
    {
        return $this->largest_expense;
    }

    /**
     * Generated from protobuf field <code>double largest_expense = 29;</code>
     * @param float $var
     * @return $this
     */
    public function setLargestExpense($var)
    {
        GPBUtil::checkDouble($var);
        $this->largest_expense = $var;

        return $this;
    }

    /**
     * Nested summaries
     *
     * Generated from protobuf field <code>.dashboard.InvestmentSummary investment_summary = 30;</code>
     * @return \Dashboard\InvestmentSummary|null
     */
    public function getInvestmentSummary()
    {
        return $this->investment_summary;
    }

    public function hasInvestmentSummary()
    {
        return isset($this->investment_summary);
    }

    public function clearInvestmentSummary()
    {
        unset($this->investment_summary);
    }

    /**
     * Nested summaries
     *
     * Generated from protobuf field <code>.dashboard.InvestmentSummary investment_summary = 30;</code>
     * @param \Dashboard\InvestmentSummary $var
     * @return $this
     */
    public function setInvestmentSummary($var)
    {
        GPBUtil::checkMessage($var, \Dashboard\InvestmentSummary::class);
        $this->investment_summary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dashboard.NetWorthSummary net_worth = 31;</code>
     * @return \Dashboard\NetWorthSummary|null
     */
    public function getNetWorth()
    {
        return $this->net_worth;
    }

    public function hasNetWorth()
    {
        return isset($this->net_worth);
    }

    public function clearNetWorth()
    {
        unset($this->net_worth);
    }

    /**
     * Generated from protobuf field <code>.dashboard.NetWorthSummary net_worth = 31;</code>
     * @param \Dashboard\NetWorthSummary $var
     * @return $this
     */
    public function setNetWorth($var)
    {
        GPBUtil::checkMessage($var, \Dashboard\NetWorthSummary::class);
        $this->net_worth = $var;

        return $this;
    }

    /**
     * Top categories
     *
     * Generated from protobuf field <code>repeated .dashboard.CategorySummary top_expense_categories = 32;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopExpenseCategories()
    {
        return $this->top_expense_categories;
    }

    /**
     * Top categories
     *
     * Generated from protobuf field <code>repeated .dashboard.CategorySummary top_expense_categories = 32;</code>
     * @param array<\Dashboard\CategorySummary>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopExpenseCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dashboard\CategorySummary::class);
        $this->top_expense_categories = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .dashboard.CategorySummary top_income_categories = 33;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopIncomeCategories()
    {
        return $this->top_income_categories;
    }

    /**
     * Generated from protobuf field <code>repeated .dashboard.CategorySummary top_income_categories = 33;</code>
     * @param array<\Dashboard\CategorySummary>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopIncomeCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dashboard\CategorySummary::class);
        $this->top_income_categories = $arr;

        return $this;
    }

    /**
     * Per wallet breakdown
     *
     * Generated from protobuf field <code>repeated .dashboard.WalletSummary wallet_summaries = 34;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWalletSummaries()
    {
        return $this->wallet_summaries;
    }

    /**
     * Per wallet breakdown
     *
     * Generated from protobuf field <code>repeated .dashboard.WalletSummary wallet_summaries = 34;</code>
     * @param array<\Dashboard\WalletSummary>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWalletSummaries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dashboard\WalletSummary::class);
        $this->wallet_summaries = $arr;

        return $this;
    }

}

