<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.GetUserBalanceRequest</code>
 */
class GetUserBalanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string wallet_id = 2;</code>
     */
    protected $wallet_id = '';
    /**
     * "daily" | "weekly" | "monthly"
     *
     * Generated from protobuf field <code>string aggregation = 3;</code>
     */
    protected $aggregation = '';
    /**
     * Generated from protobuf field <code>.dashboard.DateRange range = 4;</code>
     */
    protected $range = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $wallet_id
     *     @type string $aggregation
     *           "daily" | "weekly" | "monthly"
     *     @type \Dashboard\DateRange $range
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 2;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * "daily" | "weekly" | "monthly"
     *
     * Generated from protobuf field <code>string aggregation = 3;</code>
     * @return string
     */
    public function getAggregation()
    {
        return $this->aggregation;
    }

    /**
     * "daily" | "weekly" | "monthly"
     *
     * Generated from protobuf field <code>string aggregation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAggregation($var)
    {
        GPBUtil::checkString($var, True);
        $this->aggregation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.dashboard.DateRange range = 4;</code>
     * @return \Dashboard\DateRange|null
     */
    public function getRange()
    {
        return $this->range;
    }

    public function hasRange()
    {
        return isset($this->range);
    }

    public function clearRange()
    {
        unset($this->range);
    }

    /**
     * Generated from protobuf field <code>.dashboard.DateRange range = 4;</code>
     * @param \Dashboard\DateRange $var
     * @return $this
     */
    public function setRange($var)
    {
        GPBUtil::checkMessage($var, \Dashboard\DateRange::class);
        $this->range = $var;

        return $this;
    }

}

