<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.NetWorthSummary</code>
 */
class NetWorthSummary extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double total = 1;</code>
     */
    protected $total = 0.0;
    /**
     * Generated from protobuf field <code>double wallet_portion = 2;</code>
     */
    protected $wallet_portion = 0.0;
    /**
     * Generated from protobuf field <code>double investment_portion = 3;</code>
     */
    protected $investment_portion = 0.0;
    /**
     * Generated from protobuf field <code>double net_worth_prev = 4;</code>
     */
    protected $net_worth_prev = 0.0;
    /**
     * Generated from protobuf field <code>double net_worth_growth_pct = 5;</code>
     */
    protected $net_worth_growth_pct = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $total
     *     @type float $wallet_portion
     *     @type float $investment_portion
     *     @type float $net_worth_prev
     *     @type float $net_worth_growth_pct
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double total = 1;</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>double total = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double wallet_portion = 2;</code>
     * @return float
     */
    public function getWalletPortion()
    {
        return $this->wallet_portion;
    }

    /**
     * Generated from protobuf field <code>double wallet_portion = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWalletPortion($var)
    {
        GPBUtil::checkDouble($var);
        $this->wallet_portion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double investment_portion = 3;</code>
     * @return float
     */
    public function getInvestmentPortion()
    {
        return $this->investment_portion;
    }

    /**
     * Generated from protobuf field <code>double investment_portion = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setInvestmentPortion($var)
    {
        GPBUtil::checkDouble($var);
        $this->investment_portion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double net_worth_prev = 4;</code>
     * @return float
     */
    public function getNetWorthPrev()
    {
        return $this->net_worth_prev;
    }

    /**
     * Generated from protobuf field <code>double net_worth_prev = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setNetWorthPrev($var)
    {
        GPBUtil::checkDouble($var);
        $this->net_worth_prev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double net_worth_growth_pct = 5;</code>
     * @return float
     */
    public function getNetWorthGrowthPct()
    {
        return $this->net_worth_growth_pct;
    }

    /**
     * Generated from protobuf field <code>double net_worth_growth_pct = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setNetWorthGrowthPct($var)
    {
        GPBUtil::checkDouble($var);
        $this->net_worth_growth_pct = $var;

        return $this;
    }

}

