<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.NetWorthComposition</code>
 */
class NetWorthComposition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>double total = 2;</code>
     */
    protected $total = 0.0;
    /**
     * Generated from protobuf field <code>repeated .dashboard.NetWorthSlice slices = 3;</code>
     */
    private $slices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type float $total
     *     @type array<\Dashboard\NetWorthSlice>|\Google\Protobuf\Internal\RepeatedField $slices
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total = 2;</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>double total = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .dashboard.NetWorthSlice slices = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSlices()
    {
        return $this->slices;
    }

    /**
     * Generated from protobuf field <code>repeated .dashboard.NetWorthSlice slices = 3;</code>
     * @param array<\Dashboard\NetWorthSlice>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSlices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Dashboard\NetWorthSlice::class);
        $this->slices = $arr;

        return $this;
    }

}

