<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard/dashboard.proto

namespace Dashboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>dashboard.NetWorthSliceDetails</code>
 */
class NetWorthSliceDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 item_count = 1;</code>
     */
    protected $item_count = 0;
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double unrealized_gain = 3;</code>
     */
    protected $unrealized_gain = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $item_count
     *     @type string $description
     *     @type float $unrealized_gain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dashboard\Dashboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 item_count = 1;</code>
     * @return int
     */
    public function getItemCount()
    {
        return $this->item_count;
    }

    /**
     * Generated from protobuf field <code>int32 item_count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setItemCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->item_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double unrealized_gain = 3;</code>
     * @return float
     */
    public function getUnrealizedGain()
    {
        return $this->unrealized_gain;
    }

    /**
     * Generated from protobuf field <code>double unrealized_gain = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setUnrealizedGain($var)
    {
        GPBUtil::checkDouble($var);
        $this->unrealized_gain = $var;

        return $this;
    }

}

