<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler/scheduler.proto

namespace Scheduler;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>scheduler.CreateScheduledJobRequest</code>
 */
class CreateScheduledJobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>string schedule_type = 2;</code>
     */
    protected $schedule_type = '';
    /**
     * Generated from protobuf field <code>string job_type = 3;</code>
     */
    protected $job_type = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string wallet_id = 6;</code>
     */
    protected $wallet_id = '';
    /**
     * Generated from protobuf field <code>string category_id = 7;</code>
     */
    protected $category_id = '';
    /**
     * Generated from protobuf field <code>string asset_code = 8;</code>
     */
    protected $asset_code = '';
    /**
     * Generated from protobuf field <code>string repeat_interval = 9;</code>
     */
    protected $repeat_interval = '';
    /**
     * Generated from protobuf field <code>string repeat_detail = 10;</code>
     */
    protected $repeat_detail = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_date = 11;</code>
     */
    protected $start_date = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_date = 12;</code>
     */
    protected $end_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $schedule_type
     *     @type string $job_type
     *     @type string $description
     *     @type float $amount
     *     @type string $wallet_id
     *     @type string $category_id
     *     @type string $asset_code
     *     @type string $repeat_interval
     *     @type string $repeat_detail
     *     @type \Google\Protobuf\Timestamp $start_date
     *     @type \Google\Protobuf\Timestamp $end_date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Scheduler\Scheduler::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schedule_type = 2;</code>
     * @return string
     */
    public function getScheduleType()
    {
        return $this->schedule_type;
    }

    /**
     * Generated from protobuf field <code>string schedule_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setScheduleType($var)
    {
        GPBUtil::checkString($var, True);
        $this->schedule_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string job_type = 3;</code>
     * @return string
     */
    public function getJobType()
    {
        return $this->job_type;
    }

    /**
     * Generated from protobuf field <code>string job_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setJobType($var)
    {
        GPBUtil::checkString($var, True);
        $this->job_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 6;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_id = 7;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * Generated from protobuf field <code>string category_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string asset_code = 8;</code>
     * @return string
     */
    public function getAssetCode()
    {
        return $this->asset_code;
    }

    /**
     * Generated from protobuf field <code>string asset_code = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAssetCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->asset_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string repeat_interval = 9;</code>
     * @return string
     */
    public function getRepeatInterval()
    {
        return $this->repeat_interval;
    }

    /**
     * Generated from protobuf field <code>string repeat_interval = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setRepeatInterval($var)
    {
        GPBUtil::checkString($var, True);
        $this->repeat_interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string repeat_detail = 10;</code>
     * @return string
     */
    public function getRepeatDetail()
    {
        return $this->repeat_detail;
    }

    /**
     * Generated from protobuf field <code>string repeat_detail = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRepeatDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->repeat_detail = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_date = 11;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    public function hasStartDate()
    {
        return isset($this->start_date);
    }

    public function clearStartDate()
    {
        unset($this->start_date);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_date = 11;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_date = 12;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    public function hasEndDate()
    {
        return isset($this->end_date);
    }

    public function clearEndDate()
    {
        unset($this->end_date);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_date = 12;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_date = $var;

        return $this;
    }

}

