// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: scheduler/scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduledJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScheduleType   string                 `protobuf:"bytes,3,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"`
	JobType        string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Amount         float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletId       string                 `protobuf:"bytes,7,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	WalletName     string                 `protobuf:"bytes,8,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	CategoryId     string                 `protobuf:"bytes,9,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName   string                 `protobuf:"bytes,10,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	AssetCode      string                 `protobuf:"bytes,11,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	RepeatInterval string                 `protobuf:"bytes,12,opt,name=repeat_interval,json=repeatInterval,proto3" json:"repeat_interval,omitempty"`
	RepeatDetail   string                 `protobuf:"bytes,13,opt,name=repeat_detail,json=repeatDetail,proto3" json:"repeat_detail,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status         string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	NextExecution  *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=next_execution,json=nextExecution,proto3" json:"next_execution,omitempty"`
	LastExecution  *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=last_execution,json=lastExecution,proto3" json:"last_execution,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExecutionLogs  []*JobExecutionLog     `protobuf:"bytes,20,rep,name=execution_logs,json=executionLogs,proto3" json:"execution_logs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduledJob) Reset() {
	*x = ScheduledJob{}
	mi := &file_scheduler_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledJob) ProtoMessage() {}

func (x *ScheduledJob) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledJob.ProtoReflect.Descriptor instead.
func (*ScheduledJob) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledJob) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScheduledJob) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *ScheduledJob) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ScheduledJob) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScheduledJob) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScheduledJob) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ScheduledJob) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *ScheduledJob) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ScheduledJob) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ScheduledJob) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *ScheduledJob) GetRepeatInterval() string {
	if x != nil {
		return x.RepeatInterval
	}
	return ""
}

func (x *ScheduledJob) GetRepeatDetail() string {
	if x != nil {
		return x.RepeatDetail
	}
	return ""
}

func (x *ScheduledJob) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ScheduledJob) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *ScheduledJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduledJob) GetNextExecution() *timestamppb.Timestamp {
	if x != nil {
		return x.NextExecution
	}
	return nil
}

func (x *ScheduledJob) GetLastExecution() *timestamppb.Timestamp {
	if x != nil {
		return x.LastExecution
	}
	return nil
}

func (x *ScheduledJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScheduledJob) GetExecutionLogs() []*JobExecutionLog {
	if x != nil {
		return x.ExecutionLogs
	}
	return nil
}

type JobExecutionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobExecutionLog) Reset() {
	*x = JobExecutionLog{}
	mi := &file_scheduler_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecutionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecutionLog) ProtoMessage() {}

func (x *JobExecutionLog) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecutionLog.ProtoReflect.Descriptor instead.
func (*JobExecutionLog) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *JobExecutionLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobExecutionLog) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobExecutionLog) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *JobExecutionLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobExecutionLog) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetScheduledJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledJobsRequest) Reset() {
	*x = GetScheduledJobsRequest{}
	mi := &file_scheduler_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledJobsRequest) ProtoMessage() {}

func (x *GetScheduledJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledJobsRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledJobsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GetScheduledJobsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetScheduledJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetScheduledJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*ScheduledJob        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledJobsResponse) Reset() {
	*x = GetScheduledJobsResponse{}
	mi := &file_scheduler_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledJobsResponse) ProtoMessage() {}

func (x *GetScheduledJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledJobsResponse.ProtoReflect.Descriptor instead.
func (*GetScheduledJobsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetScheduledJobsResponse) GetJobs() []*ScheduledJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CreateScheduledJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScheduleType   string                 `protobuf:"bytes,2,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"`
	JobType        string                 `protobuf:"bytes,3,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount         float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletId       string                 `protobuf:"bytes,6,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CategoryId     string                 `protobuf:"bytes,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	AssetCode      string                 `protobuf:"bytes,8,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	RepeatInterval string                 `protobuf:"bytes,9,opt,name=repeat_interval,json=repeatInterval,proto3" json:"repeat_interval,omitempty"`
	RepeatDetail   string                 `protobuf:"bytes,10,opt,name=repeat_detail,json=repeatDetail,proto3" json:"repeat_detail,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateScheduledJobRequest) Reset() {
	*x = CreateScheduledJobRequest{}
	mi := &file_scheduler_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledJobRequest) ProtoMessage() {}

func (x *CreateScheduledJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledJobRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduledJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *CreateScheduledJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateScheduledJobRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetRepeatInterval() string {
	if x != nil {
		return x.RepeatInterval
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetRepeatDetail() string {
	if x != nil {
		return x.RepeatDetail
	}
	return ""
}

func (x *CreateScheduledJobRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateScheduledJobRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type UpdateScheduledJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	WalletId       string                 `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CategoryId     string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	AssetCode      string                 `protobuf:"bytes,6,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	RepeatInterval string                 `protobuf:"bytes,7,opt,name=repeat_interval,json=repeatInterval,proto3" json:"repeat_interval,omitempty"`
	RepeatDetail   string                 `protobuf:"bytes,8,opt,name=repeat_detail,json=repeatDetail,proto3" json:"repeat_detail,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserId         string                 `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateScheduledJobRequest) Reset() {
	*x = UpdateScheduledJobRequest{}
	mi := &file_scheduler_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledJobRequest) ProtoMessage() {}

func (x *UpdateScheduledJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduledJobRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateScheduledJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateScheduledJobRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetRepeatInterval() string {
	if x != nil {
		return x.RepeatInterval
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetRepeatDetail() string {
	if x != nil {
		return x.RepeatDetail
	}
	return ""
}

func (x *UpdateScheduledJobRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateScheduledJobRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateScheduledJobRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ScheduledJobID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledJobID) Reset() {
	*x = ScheduledJobID{}
	mi := &file_scheduler_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledJobID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledJobID) ProtoMessage() {}

func (x *ScheduledJobID) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledJobID.ProtoReflect.Descriptor instead.
func (*ScheduledJobID) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduledJobID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduledJobID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetJobExecutionLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobExecutionLogsRequest) Reset() {
	*x = GetJobExecutionLogsRequest{}
	mi := &file_scheduler_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobExecutionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobExecutionLogsRequest) ProtoMessage() {}

func (x *GetJobExecutionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobExecutionLogsRequest.ProtoReflect.Descriptor instead.
func (*GetJobExecutionLogsRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *GetJobExecutionLogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobExecutionLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetJobExecutionLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetJobExecutionLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetJobExecutionLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*JobExecutionLog     `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobExecutionLogsResponse) Reset() {
	*x = GetJobExecutionLogsResponse{}
	mi := &file_scheduler_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobExecutionLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobExecutionLogsResponse) ProtoMessage() {}

func (x *GetJobExecutionLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobExecutionLogsResponse.ProtoReflect.Descriptor instead.
func (*GetJobExecutionLogsResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobExecutionLogsResponse) GetLogs() []*JobExecutionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_scheduler_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19scheduler/scheduler.proto\x12\tscheduler\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x06\n" +
	"\fScheduledJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rschedule_type\x18\x03 \x01(\tR\fscheduleType\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x1b\n" +
	"\twallet_id\x18\a \x01(\tR\bwalletId\x12\x1f\n" +
	"\vwallet_name\x18\b \x01(\tR\n" +
	"walletName\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\n" +
	" \x01(\tR\fcategoryName\x12\x1d\n" +
	"\n" +
	"asset_code\x18\v \x01(\tR\tassetCode\x12'\n" +
	"\x0frepeat_interval\x18\f \x01(\tR\x0erepeatInterval\x12#\n" +
	"\rrepeat_detail\x18\r \x01(\tR\frepeatDetail\x129\n" +
	"\n" +
	"start_date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12A\n" +
	"\x0enext_execution\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\rnextExecution\x12A\n" +
	"\x0elast_execution\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\rlastExecution\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\x0eexecution_logs\x18\x14 \x03(\v2\x1a.scheduler.JobExecutionLogR\rexecutionLogs\"\xa5\x01\n" +
	"\x0fJobExecutionLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12;\n" +
	"\vexecuted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"J\n" +
	"\x17GetScheduledJobsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"G\n" +
	"\x18GetScheduledJobsResponse\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.scheduler.ScheduledJobR\x04jobs\"\xcb\x03\n" +
	"\x19CreateScheduledJobRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rschedule_type\x18\x02 \x01(\tR\fscheduleType\x12\x19\n" +
	"\bjob_type\x18\x03 \x01(\tR\ajobType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1b\n" +
	"\twallet_id\x18\x06 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"asset_code\x18\b \x01(\tR\tassetCode\x12'\n" +
	"\x0frepeat_interval\x18\t \x01(\tR\x0erepeatInterval\x12#\n" +
	"\rrepeat_detail\x18\n" +
	" \x01(\tR\frepeatDetail\x129\n" +
	"\n" +
	"start_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x9b\x03\n" +
	"\x19UpdateScheduledJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1b\n" +
	"\twallet_id\x18\x04 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x06 \x01(\tR\tassetCode\x12'\n" +
	"\x0frepeat_interval\x18\a \x01(\tR\x0erepeatInterval\x12#\n" +
	"\rrepeat_detail\x18\b \x01(\tR\frepeatDetail\x129\n" +
	"\n" +
	"start_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\"9\n" +
	"\x0eScheduledJobID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"z\n" +
	"\x1aGetJobExecutionLogsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"M\n" +
	"\x1bGetJobExecutionLogsResponse\x12.\n" +
	"\x04logs\x18\x01 \x03(\v2\x1a.scheduler.JobExecutionLogR\x04logs2\xea\x04\n" +
	"\x10SchedulerService\x12]\n" +
	"\x10GetScheduledJobs\x12\".scheduler.GetScheduledJobsRequest\x1a#.scheduler.GetScheduledJobsResponse\"\x00\x12U\n" +
	"\x12CreateScheduledJob\x12$.scheduler.CreateScheduledJobRequest\x1a\x17.scheduler.ScheduledJob\"\x00\x12U\n" +
	"\x12UpdateScheduledJob\x12$.scheduler.UpdateScheduledJobRequest\x1a\x17.scheduler.ScheduledJob\"\x00\x12I\n" +
	"\x11PauseScheduledJob\x12\x19.scheduler.ScheduledJobID\x1a\x17.scheduler.ScheduledJob\"\x00\x12J\n" +
	"\x12ResumeScheduledJob\x12\x19.scheduler.ScheduledJobID\x1a\x17.scheduler.ScheduledJob\"\x00\x12J\n" +
	"\x12DeleteScheduledJob\x12\x19.scheduler.ScheduledJobID\x1a\x17.scheduler.ScheduledJob\"\x00\x12f\n" +
	"\x13GetJobExecutionLogs\x12%.scheduler.GetJobExecutionLogsRequest\x1a&.scheduler.GetJobExecutionLogsResponse\"\x00B5Z3github.com/MuhammadMiftaa/Refina-Protobuf/schedulerb\x06proto3"

var (
	file_scheduler_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_scheduler_proto_rawDescData []byte
)

func file_scheduler_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_scheduler_proto_rawDesc), len(file_scheduler_scheduler_proto_rawDesc)))
	})
	return file_scheduler_scheduler_proto_rawDescData
}

var file_scheduler_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_scheduler_scheduler_proto_goTypes = []any{
	(*ScheduledJob)(nil),                // 0: scheduler.ScheduledJob
	(*JobExecutionLog)(nil),             // 1: scheduler.JobExecutionLog
	(*GetScheduledJobsRequest)(nil),     // 2: scheduler.GetScheduledJobsRequest
	(*GetScheduledJobsResponse)(nil),    // 3: scheduler.GetScheduledJobsResponse
	(*CreateScheduledJobRequest)(nil),   // 4: scheduler.CreateScheduledJobRequest
	(*UpdateScheduledJobRequest)(nil),   // 5: scheduler.UpdateScheduledJobRequest
	(*ScheduledJobID)(nil),              // 6: scheduler.ScheduledJobID
	(*GetJobExecutionLogsRequest)(nil),  // 7: scheduler.GetJobExecutionLogsRequest
	(*GetJobExecutionLogsResponse)(nil), // 8: scheduler.GetJobExecutionLogsResponse
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_scheduler_scheduler_proto_depIdxs = []int32{
	9,  // 0: scheduler.ScheduledJob.start_date:type_name -> google.protobuf.Timestamp
	9,  // 1: scheduler.ScheduledJob.end_date:type_name -> google.protobuf.Timestamp
	9,  // 2: scheduler.ScheduledJob.next_execution:type_name -> google.protobuf.Timestamp
	9,  // 3: scheduler.ScheduledJob.last_execution:type_name -> google.protobuf.Timestamp
	9,  // 4: scheduler.ScheduledJob.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: scheduler.ScheduledJob.execution_logs:type_name -> scheduler.JobExecutionLog
	9,  // 6: scheduler.JobExecutionLog.executed_at:type_name -> google.protobuf.Timestamp
	0,  // 7: scheduler.GetScheduledJobsResponse.jobs:type_name -> scheduler.ScheduledJob
	9,  // 8: scheduler.CreateScheduledJobRequest.start_date:type_name -> google.protobuf.Timestamp
	9,  // 9: scheduler.CreateScheduledJobRequest.end_date:type_name -> google.protobuf.Timestamp
	9,  // 10: scheduler.UpdateScheduledJobRequest.start_date:type_name -> google.protobuf.Timestamp
	9,  // 11: scheduler.UpdateScheduledJobRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 12: scheduler.GetJobExecutionLogsResponse.logs:type_name -> scheduler.JobExecutionLog
	2,  // 13: scheduler.SchedulerService.GetScheduledJobs:input_type -> scheduler.GetScheduledJobsRequest
	4,  // 14: scheduler.SchedulerService.CreateScheduledJob:input_type -> scheduler.CreateScheduledJobRequest
	5,  // 15: scheduler.SchedulerService.UpdateScheduledJob:input_type -> scheduler.UpdateScheduledJobRequest
	6,  // 16: scheduler.SchedulerService.PauseScheduledJob:input_type -> scheduler.ScheduledJobID
	6,  // 17: scheduler.SchedulerService.ResumeScheduledJob:input_type -> scheduler.ScheduledJobID
	6,  // 18: scheduler.SchedulerService.DeleteScheduledJob:input_type -> scheduler.ScheduledJobID
	7,  // 19: scheduler.SchedulerService.GetJobExecutionLogs:input_type -> scheduler.GetJobExecutionLogsRequest
	3,  // 20: scheduler.SchedulerService.GetScheduledJobs:output_type -> scheduler.GetScheduledJobsResponse
	0,  // 21: scheduler.SchedulerService.CreateScheduledJob:output_type -> scheduler.ScheduledJob
	0,  // 22: scheduler.SchedulerService.UpdateScheduledJob:output_type -> scheduler.ScheduledJob
	0,  // 23: scheduler.SchedulerService.PauseScheduledJob:output_type -> scheduler.ScheduledJob
	0,  // 24: scheduler.SchedulerService.ResumeScheduledJob:output_type -> scheduler.ScheduledJob
	0,  // 25: scheduler.SchedulerService.DeleteScheduledJob:output_type -> scheduler.ScheduledJob
	8,  // 26: scheduler.SchedulerService.GetJobExecutionLogs:output_type -> scheduler.GetJobExecutionLogsResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_scheduler_scheduler_proto_init() }
func file_scheduler_scheduler_proto_init() {
	if File_scheduler_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_scheduler_proto_rawDesc), len(file_scheduler_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_scheduler_proto = out.File
	file_scheduler_scheduler_proto_goTypes = nil
	file_scheduler_scheduler_proto_depIdxs = nil
}
