// source: scheduler/scheduler.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.scheduler.CreateScheduledJobRequest', null, global);
goog.exportSymbol('proto.scheduler.GetJobExecutionLogsRequest', null, global);
goog.exportSymbol('proto.scheduler.GetJobExecutionLogsResponse', null, global);
goog.exportSymbol('proto.scheduler.GetScheduledJobsRequest', null, global);
goog.exportSymbol('proto.scheduler.GetScheduledJobsResponse', null, global);
goog.exportSymbol('proto.scheduler.JobExecutionLog', null, global);
goog.exportSymbol('proto.scheduler.ScheduledJob', null, global);
goog.exportSymbol('proto.scheduler.ScheduledJobID', null, global);
goog.exportSymbol('proto.scheduler.UpdateScheduledJobRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.ScheduledJob = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.scheduler.ScheduledJob.repeatedFields_, null);
};
goog.inherits(proto.scheduler.ScheduledJob, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.ScheduledJob.displayName = 'proto.scheduler.ScheduledJob';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.JobExecutionLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scheduler.JobExecutionLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.JobExecutionLog.displayName = 'proto.scheduler.JobExecutionLog';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.GetScheduledJobsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scheduler.GetScheduledJobsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.GetScheduledJobsRequest.displayName = 'proto.scheduler.GetScheduledJobsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.GetScheduledJobsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.scheduler.GetScheduledJobsResponse.repeatedFields_, null);
};
goog.inherits(proto.scheduler.GetScheduledJobsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.GetScheduledJobsResponse.displayName = 'proto.scheduler.GetScheduledJobsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.CreateScheduledJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scheduler.CreateScheduledJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.CreateScheduledJobRequest.displayName = 'proto.scheduler.CreateScheduledJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.UpdateScheduledJobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scheduler.UpdateScheduledJobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.UpdateScheduledJobRequest.displayName = 'proto.scheduler.UpdateScheduledJobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.ScheduledJobID = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scheduler.ScheduledJobID, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.ScheduledJobID.displayName = 'proto.scheduler.ScheduledJobID';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.GetJobExecutionLogsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.scheduler.GetJobExecutionLogsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.GetJobExecutionLogsRequest.displayName = 'proto.scheduler.GetJobExecutionLogsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scheduler.GetJobExecutionLogsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.scheduler.GetJobExecutionLogsResponse.repeatedFields_, null);
};
goog.inherits(proto.scheduler.GetJobExecutionLogsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scheduler.GetJobExecutionLogsResponse.displayName = 'proto.scheduler.GetJobExecutionLogsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.scheduler.ScheduledJob.repeatedFields_ = [20];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.ScheduledJob.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.ScheduledJob.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.ScheduledJob} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.ScheduledJob.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    scheduleType: jspb.Message.getFieldWithDefault(msg, 3, ""),
    jobType: jspb.Message.getFieldWithDefault(msg, 4, ""),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    walletId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    walletName: jspb.Message.getFieldWithDefault(msg, 8, ""),
    categoryId: jspb.Message.getFieldWithDefault(msg, 9, ""),
    categoryName: jspb.Message.getFieldWithDefault(msg, 10, ""),
    assetCode: jspb.Message.getFieldWithDefault(msg, 11, ""),
    repeatInterval: jspb.Message.getFieldWithDefault(msg, 12, ""),
    repeatDetail: jspb.Message.getFieldWithDefault(msg, 13, ""),
    startDate: (f = msg.getStartDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endDate: (f = msg.getEndDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 16, ""),
    nextExecution: (f = msg.getNextExecution()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lastExecution: (f = msg.getLastExecution()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    executionLogsList: jspb.Message.toObjectList(msg.getExecutionLogsList(),
    proto.scheduler.JobExecutionLog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.ScheduledJob}
 */
proto.scheduler.ScheduledJob.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.ScheduledJob;
  return proto.scheduler.ScheduledJob.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.ScheduledJob} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.ScheduledJob}
 */
proto.scheduler.ScheduledJob.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setScheduleType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletName(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoryId(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoryName(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssetCode(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepeatInterval(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepeatDetail(value);
      break;
    case 14:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartDate(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndDate(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 17:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setNextExecution(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastExecution(value);
      break;
    case 19:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 20:
      var value = new proto.scheduler.JobExecutionLog;
      reader.readMessage(value,proto.scheduler.JobExecutionLog.deserializeBinaryFromReader);
      msg.addExecutionLogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.ScheduledJob.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.ScheduledJob.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.ScheduledJob} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.ScheduledJob.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getScheduleType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getJobType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getWalletId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWalletName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCategoryId();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCategoryName();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAssetCode();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getRepeatInterval();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getRepeatDetail();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getStartDate();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndDate();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getNextExecution();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLastExecution();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExecutionLogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.scheduler.JobExecutionLog.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 2;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string schedule_type = 3;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getScheduleType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setScheduleType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string job_type = 4;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getJobType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setJobType = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional double amount = 6;
 * @return {number}
 */
proto.scheduler.ScheduledJob.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string wallet_id = 7;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getWalletId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setWalletId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string wallet_name = 8;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getWalletName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setWalletName = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string category_id = 9;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getCategoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setCategoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string category_name = 10;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getCategoryName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setCategoryName = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string asset_code = 11;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getAssetCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setAssetCode = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string repeat_interval = 12;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getRepeatInterval = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setRepeatInterval = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string repeat_detail = 13;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getRepeatDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setRepeatDetail = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional google.protobuf.Timestamp start_date = 14;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.ScheduledJob.prototype.getStartDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 14));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.ScheduledJob} returns this
*/
proto.scheduler.ScheduledJob.prototype.setStartDate = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.clearStartDate = function() {
  return this.setStartDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.ScheduledJob.prototype.hasStartDate = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional google.protobuf.Timestamp end_date = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.ScheduledJob.prototype.getEndDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.ScheduledJob} returns this
*/
proto.scheduler.ScheduledJob.prototype.setEndDate = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.clearEndDate = function() {
  return this.setEndDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.ScheduledJob.prototype.hasEndDate = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string status = 16;
 * @return {string}
 */
proto.scheduler.ScheduledJob.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional google.protobuf.Timestamp next_execution = 17;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.ScheduledJob.prototype.getNextExecution = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 17));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.ScheduledJob} returns this
*/
proto.scheduler.ScheduledJob.prototype.setNextExecution = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.clearNextExecution = function() {
  return this.setNextExecution(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.ScheduledJob.prototype.hasNextExecution = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional google.protobuf.Timestamp last_execution = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.ScheduledJob.prototype.getLastExecution = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.ScheduledJob} returns this
*/
proto.scheduler.ScheduledJob.prototype.setLastExecution = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.clearLastExecution = function() {
  return this.setLastExecution(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.ScheduledJob.prototype.hasLastExecution = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 19;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.ScheduledJob.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 19));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.ScheduledJob} returns this
*/
proto.scheduler.ScheduledJob.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.ScheduledJob.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * repeated JobExecutionLog execution_logs = 20;
 * @return {!Array<!proto.scheduler.JobExecutionLog>}
 */
proto.scheduler.ScheduledJob.prototype.getExecutionLogsList = function() {
  return /** @type{!Array<!proto.scheduler.JobExecutionLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.scheduler.JobExecutionLog, 20));
};


/**
 * @param {!Array<!proto.scheduler.JobExecutionLog>} value
 * @return {!proto.scheduler.ScheduledJob} returns this
*/
proto.scheduler.ScheduledJob.prototype.setExecutionLogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.scheduler.JobExecutionLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.scheduler.JobExecutionLog}
 */
proto.scheduler.ScheduledJob.prototype.addExecutionLogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.scheduler.JobExecutionLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.scheduler.ScheduledJob} returns this
 */
proto.scheduler.ScheduledJob.prototype.clearExecutionLogsList = function() {
  return this.setExecutionLogsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.JobExecutionLog.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.JobExecutionLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.JobExecutionLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.JobExecutionLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    jobId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    executedAt: (f = msg.getExecutedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 4, ""),
    reason: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.JobExecutionLog}
 */
proto.scheduler.JobExecutionLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.JobExecutionLog;
  return proto.scheduler.JobExecutionLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.JobExecutionLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.JobExecutionLog}
 */
proto.scheduler.JobExecutionLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExecutedAt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.JobExecutionLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.JobExecutionLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.JobExecutionLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.JobExecutionLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExecutedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.scheduler.JobExecutionLog.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.JobExecutionLog} returns this
 */
proto.scheduler.JobExecutionLog.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string job_id = 2;
 * @return {string}
 */
proto.scheduler.JobExecutionLog.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.JobExecutionLog} returns this
 */
proto.scheduler.JobExecutionLog.prototype.setJobId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp executed_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.JobExecutionLog.prototype.getExecutedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.JobExecutionLog} returns this
*/
proto.scheduler.JobExecutionLog.prototype.setExecutedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.JobExecutionLog} returns this
 */
proto.scheduler.JobExecutionLog.prototype.clearExecutedAt = function() {
  return this.setExecutedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.JobExecutionLog.prototype.hasExecutedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.scheduler.JobExecutionLog.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.JobExecutionLog} returns this
 */
proto.scheduler.JobExecutionLog.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string reason = 5;
 * @return {string}
 */
proto.scheduler.JobExecutionLog.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.JobExecutionLog} returns this
 */
proto.scheduler.JobExecutionLog.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.GetScheduledJobsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.GetScheduledJobsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.GetScheduledJobsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetScheduledJobsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.GetScheduledJobsRequest}
 */
proto.scheduler.GetScheduledJobsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.GetScheduledJobsRequest;
  return proto.scheduler.GetScheduledJobsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.GetScheduledJobsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.GetScheduledJobsRequest}
 */
proto.scheduler.GetScheduledJobsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.GetScheduledJobsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.GetScheduledJobsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.GetScheduledJobsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetScheduledJobsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.scheduler.GetScheduledJobsRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.GetScheduledJobsRequest} returns this
 */
proto.scheduler.GetScheduledJobsRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string status = 2;
 * @return {string}
 */
proto.scheduler.GetScheduledJobsRequest.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.GetScheduledJobsRequest} returns this
 */
proto.scheduler.GetScheduledJobsRequest.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.scheduler.GetScheduledJobsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.GetScheduledJobsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.GetScheduledJobsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.GetScheduledJobsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetScheduledJobsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobsList: jspb.Message.toObjectList(msg.getJobsList(),
    proto.scheduler.ScheduledJob.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.GetScheduledJobsResponse}
 */
proto.scheduler.GetScheduledJobsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.GetScheduledJobsResponse;
  return proto.scheduler.GetScheduledJobsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.GetScheduledJobsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.GetScheduledJobsResponse}
 */
proto.scheduler.GetScheduledJobsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.scheduler.ScheduledJob;
      reader.readMessage(value,proto.scheduler.ScheduledJob.deserializeBinaryFromReader);
      msg.addJobs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.GetScheduledJobsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.GetScheduledJobsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.GetScheduledJobsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetScheduledJobsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.scheduler.ScheduledJob.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ScheduledJob jobs = 1;
 * @return {!Array<!proto.scheduler.ScheduledJob>}
 */
proto.scheduler.GetScheduledJobsResponse.prototype.getJobsList = function() {
  return /** @type{!Array<!proto.scheduler.ScheduledJob>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.scheduler.ScheduledJob, 1));
};


/**
 * @param {!Array<!proto.scheduler.ScheduledJob>} value
 * @return {!proto.scheduler.GetScheduledJobsResponse} returns this
*/
proto.scheduler.GetScheduledJobsResponse.prototype.setJobsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.scheduler.ScheduledJob=} opt_value
 * @param {number=} opt_index
 * @return {!proto.scheduler.ScheduledJob}
 */
proto.scheduler.GetScheduledJobsResponse.prototype.addJobs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.scheduler.ScheduledJob, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.scheduler.GetScheduledJobsResponse} returns this
 */
proto.scheduler.GetScheduledJobsResponse.prototype.clearJobsList = function() {
  return this.setJobsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.CreateScheduledJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.CreateScheduledJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.CreateScheduledJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    scheduleType: jspb.Message.getFieldWithDefault(msg, 2, ""),
    jobType: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    walletId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    categoryId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    assetCode: jspb.Message.getFieldWithDefault(msg, 8, ""),
    repeatInterval: jspb.Message.getFieldWithDefault(msg, 9, ""),
    repeatDetail: jspb.Message.getFieldWithDefault(msg, 10, ""),
    startDate: (f = msg.getStartDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endDate: (f = msg.getEndDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.CreateScheduledJobRequest}
 */
proto.scheduler.CreateScheduledJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.CreateScheduledJobRequest;
  return proto.scheduler.CreateScheduledJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.CreateScheduledJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.CreateScheduledJobRequest}
 */
proto.scheduler.CreateScheduledJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setScheduleType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoryId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssetCode(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepeatInterval(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepeatDetail(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartDate(value);
      break;
    case 12:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.CreateScheduledJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.CreateScheduledJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.CreateScheduledJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScheduleType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getJobType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getWalletId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCategoryId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getAssetCode();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRepeatInterval();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getRepeatDetail();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getStartDate();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndDate();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string schedule_type = 2;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getScheduleType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setScheduleType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string job_type = 3;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getJobType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setJobType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional double amount = 5;
 * @return {number}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional string wallet_id = 6;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getWalletId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setWalletId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string category_id = 7;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getCategoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setCategoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string asset_code = 8;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getAssetCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setAssetCode = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string repeat_interval = 9;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getRepeatInterval = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setRepeatInterval = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string repeat_detail = 10;
 * @return {string}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getRepeatDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.setRepeatDetail = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional google.protobuf.Timestamp start_date = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getStartDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
*/
proto.scheduler.CreateScheduledJobRequest.prototype.setStartDate = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.clearStartDate = function() {
  return this.setStartDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.hasStartDate = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.Timestamp end_date = 12;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.getEndDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 12));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
*/
proto.scheduler.CreateScheduledJobRequest.prototype.setEndDate = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.CreateScheduledJobRequest} returns this
 */
proto.scheduler.CreateScheduledJobRequest.prototype.clearEndDate = function() {
  return this.setEndDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.CreateScheduledJobRequest.prototype.hasEndDate = function() {
  return jspb.Message.getField(this, 12) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.UpdateScheduledJobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.UpdateScheduledJobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.UpdateScheduledJobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    walletId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    categoryId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    assetCode: jspb.Message.getFieldWithDefault(msg, 6, ""),
    repeatInterval: jspb.Message.getFieldWithDefault(msg, 7, ""),
    repeatDetail: jspb.Message.getFieldWithDefault(msg, 8, ""),
    startDate: (f = msg.getStartDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endDate: (f = msg.getEndDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    userId: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.UpdateScheduledJobRequest}
 */
proto.scheduler.UpdateScheduledJobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.UpdateScheduledJobRequest;
  return proto.scheduler.UpdateScheduledJobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.UpdateScheduledJobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.UpdateScheduledJobRequest}
 */
proto.scheduler.UpdateScheduledJobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWalletId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoryId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssetCode(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepeatInterval(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepeatDetail(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartDate(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndDate(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.UpdateScheduledJobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.UpdateScheduledJobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.UpdateScheduledJobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getWalletId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCategoryId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAssetCode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRepeatInterval();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getRepeatDetail();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getStartDate();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndDate();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double amount = 3;
 * @return {number}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string wallet_id = 4;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getWalletId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setWalletId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string category_id = 5;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getCategoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setCategoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string asset_code = 6;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getAssetCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setAssetCode = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string repeat_interval = 7;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getRepeatInterval = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setRepeatInterval = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string repeat_detail = 8;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getRepeatDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setRepeatDetail = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional google.protobuf.Timestamp start_date = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getStartDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
*/
proto.scheduler.UpdateScheduledJobRequest.prototype.setStartDate = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.clearStartDate = function() {
  return this.setStartDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.hasStartDate = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp end_date = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getEndDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
*/
proto.scheduler.UpdateScheduledJobRequest.prototype.setEndDate = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.clearEndDate = function() {
  return this.setEndDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.hasEndDate = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string user_id = 11;
 * @return {string}
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.UpdateScheduledJobRequest} returns this
 */
proto.scheduler.UpdateScheduledJobRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.ScheduledJobID.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.ScheduledJobID.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.ScheduledJobID} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.ScheduledJobID.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.ScheduledJobID}
 */
proto.scheduler.ScheduledJobID.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.ScheduledJobID;
  return proto.scheduler.ScheduledJobID.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.ScheduledJobID} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.ScheduledJobID}
 */
proto.scheduler.ScheduledJobID.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.ScheduledJobID.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.ScheduledJobID.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.ScheduledJobID} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.ScheduledJobID.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.scheduler.ScheduledJobID.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJobID} returns this
 */
proto.scheduler.ScheduledJobID.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 2;
 * @return {string}
 */
proto.scheduler.ScheduledJobID.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.ScheduledJobID} returns this
 */
proto.scheduler.ScheduledJobID.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.GetJobExecutionLogsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.GetJobExecutionLogsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetJobExecutionLogsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    limit: jspb.Message.getFieldWithDefault(msg, 2, 0),
    offset: jspb.Message.getFieldWithDefault(msg, 3, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.GetJobExecutionLogsRequest}
 */
proto.scheduler.GetJobExecutionLogsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.GetJobExecutionLogsRequest;
  return proto.scheduler.GetJobExecutionLogsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.GetJobExecutionLogsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.GetJobExecutionLogsRequest}
 */
proto.scheduler.GetJobExecutionLogsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLimit(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOffset(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.GetJobExecutionLogsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.GetJobExecutionLogsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetJobExecutionLogsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string job_id = 1;
 * @return {string}
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.GetJobExecutionLogsRequest} returns this
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.setJobId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 limit = 2;
 * @return {number}
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.scheduler.GetJobExecutionLogsRequest} returns this
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 offset = 3;
 * @return {number}
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.scheduler.GetJobExecutionLogsRequest} returns this
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.setOffset = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string user_id = 4;
 * @return {string}
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.scheduler.GetJobExecutionLogsRequest} returns this
 */
proto.scheduler.GetJobExecutionLogsRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.scheduler.GetJobExecutionLogsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scheduler.GetJobExecutionLogsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.scheduler.GetJobExecutionLogsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scheduler.GetJobExecutionLogsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetJobExecutionLogsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    logsList: jspb.Message.toObjectList(msg.getLogsList(),
    proto.scheduler.JobExecutionLog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scheduler.GetJobExecutionLogsResponse}
 */
proto.scheduler.GetJobExecutionLogsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scheduler.GetJobExecutionLogsResponse;
  return proto.scheduler.GetJobExecutionLogsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scheduler.GetJobExecutionLogsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scheduler.GetJobExecutionLogsResponse}
 */
proto.scheduler.GetJobExecutionLogsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.scheduler.JobExecutionLog;
      reader.readMessage(value,proto.scheduler.JobExecutionLog.deserializeBinaryFromReader);
      msg.addLogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scheduler.GetJobExecutionLogsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scheduler.GetJobExecutionLogsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scheduler.GetJobExecutionLogsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scheduler.GetJobExecutionLogsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.scheduler.JobExecutionLog.serializeBinaryToWriter
    );
  }
};


/**
 * repeated JobExecutionLog logs = 1;
 * @return {!Array<!proto.scheduler.JobExecutionLog>}
 */
proto.scheduler.GetJobExecutionLogsResponse.prototype.getLogsList = function() {
  return /** @type{!Array<!proto.scheduler.JobExecutionLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.scheduler.JobExecutionLog, 1));
};


/**
 * @param {!Array<!proto.scheduler.JobExecutionLog>} value
 * @return {!proto.scheduler.GetJobExecutionLogsResponse} returns this
*/
proto.scheduler.GetJobExecutionLogsResponse.prototype.setLogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.scheduler.JobExecutionLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.scheduler.JobExecutionLog}
 */
proto.scheduler.GetJobExecutionLogsResponse.prototype.addLogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.scheduler.JobExecutionLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.scheduler.GetJobExecutionLogsResponse} returns this
 */
proto.scheduler.GetJobExecutionLogsResponse.prototype.clearLogsList = function() {
  return this.setLogsList([]);
};


goog.object.extend(exports, proto.scheduler);
