<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.GetAttachmentsResponse</code>
 */
class GetAttachmentsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .transaction.Attachment attachments = 1;</code>
     */
    private $attachments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Transaction\Attachment>|\Google\Protobuf\Internal\RepeatedField $attachments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.Attachment attachments = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.Attachment attachments = 1;</code>
     * @param array<\Transaction\Attachment>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttachments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Attachment::class);
        $this->attachments = $arr;

        return $this;
    }

}

