<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.GetUserTransactionsRequest</code>
 */
class GetUserTransactionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string wallet_ids = 1;</code>
     */
    private $wallet_ids;
    /**
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     */
    protected $page_size = 0;
    /**
     * Generated from protobuf field <code>string sort_by = 3;</code>
     */
    protected $sort_by = '';
    /**
     * Generated from protobuf field <code>string sort_order = 4;</code>
     */
    protected $sort_order = '';
    /**
     * Generated from protobuf field <code>string search = 5;</code>
     */
    protected $search = '';
    /**
     * Generated from protobuf field <code>string wallet_id = 6;</code>
     */
    protected $wallet_id = '';
    /**
     * Generated from protobuf field <code>string category_id = 7;</code>
     */
    protected $category_id = '';
    /**
     * Generated from protobuf field <code>string category_type = 8;</code>
     */
    protected $category_type = '';
    /**
     * Generated from protobuf field <code>string date_from = 9;</code>
     */
    protected $date_from = '';
    /**
     * Generated from protobuf field <code>string date_to = 10;</code>
     */
    protected $date_to = '';
    /**
     * keyset cursor (last item ID from previous page)
     *
     * Generated from protobuf field <code>string cursor = 11;</code>
     */
    protected $cursor = '';
    /**
     * cursor sort value when sorting by amount
     *
     * Generated from protobuf field <code>double cursor_amount = 12;</code>
     */
    protected $cursor_amount = 0.0;
    /**
     * cursor sort value when sorting by date
     *
     * Generated from protobuf field <code>string cursor_date = 13;</code>
     */
    protected $cursor_date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $wallet_ids
     *     @type int $page_size
     *     @type string $sort_by
     *     @type string $sort_order
     *     @type string $search
     *     @type string $wallet_id
     *     @type string $category_id
     *     @type string $category_type
     *     @type string $date_from
     *     @type string $date_to
     *     @type string $cursor
     *           keyset cursor (last item ID from previous page)
     *     @type float $cursor_amount
     *           cursor sort value when sorting by amount
     *     @type string $cursor_date
     *           cursor sort value when sorting by date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string wallet_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWalletIds()
    {
        return $this->wallet_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string wallet_ids = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWalletIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->wallet_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sort_by = 3;</code>
     * @return string
     */
    public function getSortBy()
    {
        return $this->sort_by;
    }

    /**
     * Generated from protobuf field <code>string sort_by = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSortBy($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sort_order = 4;</code>
     * @return string
     */
    public function getSortOrder()
    {
        return $this->sort_order;
    }

    /**
     * Generated from protobuf field <code>string sort_order = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSortOrder($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort_order = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string search = 5;</code>
     * @return string
     */
    public function getSearch()
    {
        return $this->search;
    }

    /**
     * Generated from protobuf field <code>string search = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 6;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_id = 7;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * Generated from protobuf field <code>string category_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_type = 8;</code>
     * @return string
     */
    public function getCategoryType()
    {
        return $this->category_type;
    }

    /**
     * Generated from protobuf field <code>string category_type = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryType($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date_from = 9;</code>
     * @return string
     */
    public function getDateFrom()
    {
        return $this->date_from;
    }

    /**
     * Generated from protobuf field <code>string date_from = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDateFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date_to = 10;</code>
     * @return string
     */
    public function getDateTo()
    {
        return $this->date_to;
    }

    /**
     * Generated from protobuf field <code>string date_to = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDateTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_to = $var;

        return $this;
    }

    /**
     * keyset cursor (last item ID from previous page)
     *
     * Generated from protobuf field <code>string cursor = 11;</code>
     * @return string
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    /**
     * keyset cursor (last item ID from previous page)
     *
     * Generated from protobuf field <code>string cursor = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkString($var, True);
        $this->cursor = $var;

        return $this;
    }

    /**
     * cursor sort value when sorting by amount
     *
     * Generated from protobuf field <code>double cursor_amount = 12;</code>
     * @return float
     */
    public function getCursorAmount()
    {
        return $this->cursor_amount;
    }

    /**
     * cursor sort value when sorting by amount
     *
     * Generated from protobuf field <code>double cursor_amount = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setCursorAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->cursor_amount = $var;

        return $this;
    }

    /**
     * cursor sort value when sorting by date
     *
     * Generated from protobuf field <code>string cursor_date = 13;</code>
     * @return string
     */
    public function getCursorDate()
    {
        return $this->cursor_date;
    }

    /**
     * cursor sort value when sorting by date
     *
     * Generated from protobuf field <code>string cursor_date = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setCursorDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->cursor_date = $var;

        return $this;
    }

}

