<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.TransactionDetail</code>
 */
class TransactionDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string wallet_id = 2;</code>
     */
    protected $wallet_id = '';
    /**
     * Generated from protobuf field <code>string category_id = 3;</code>
     */
    protected $category_id = '';
    /**
     * Generated from protobuf field <code>string category_name = 4;</code>
     */
    protected $category_name = '';
    /**
     * Generated from protobuf field <code>string category_type = 5;</code>
     */
    protected $category_type = '';
    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string transaction_date = 7;</code>
     */
    protected $transaction_date = '';
    /**
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string created_at = 9;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>string wallet_name = 11;</code>
     */
    protected $wallet_name = '';
    /**
     * Generated from protobuf field <code>repeated .transaction.Attachment attachments = 12;</code>
     */
    private $attachments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $wallet_id
     *     @type string $category_id
     *     @type string $category_name
     *     @type string $category_type
     *     @type float $amount
     *     @type string $transaction_date
     *     @type string $description
     *     @type string $created_at
     *     @type string $updated_at
     *     @type string $wallet_name
     *     @type array<\Transaction\Attachment>|\Google\Protobuf\Internal\RepeatedField $attachments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 2;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_id = 3;</code>
     * @return string
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * Generated from protobuf field <code>string category_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryId($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_name = 4;</code>
     * @return string
     */
    public function getCategoryName()
    {
        return $this->category_name;
    }

    /**
     * Generated from protobuf field <code>string category_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category_type = 5;</code>
     * @return string
     */
    public function getCategoryType()
    {
        return $this->category_type;
    }

    /**
     * Generated from protobuf field <code>string category_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryType($var)
    {
        GPBUtil::checkString($var, True);
        $this->category_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_date = 7;</code>
     * @return string
     */
    public function getTransactionDate()
    {
        return $this->transaction_date;
    }

    /**
     * Generated from protobuf field <code>string transaction_date = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 9;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_name = 11;</code>
     * @return string
     */
    public function getWalletName()
    {
        return $this->wallet_name;
    }

    /**
     * Generated from protobuf field <code>string wallet_name = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletName($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.Attachment attachments = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * Generated from protobuf field <code>repeated .transaction.Attachment attachments = 12;</code>
     * @param array<\Transaction\Attachment>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttachments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Transaction\Attachment::class);
        $this->attachments = $arr;

        return $this;
    }

}

