<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: investment/investment.proto

namespace Investment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>investment.AssetCode</code>
 */
class AssetCode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string unit = 3;</code>
     */
    protected $unit = '';
    /**
     * Generated from protobuf field <code>double toUSD = 4;</code>
     */
    protected $toUSD = 0.0;
    /**
     * Generated from protobuf field <code>double toEUR = 5;</code>
     */
    protected $toEUR = 0.0;
    /**
     * Generated from protobuf field <code>double toIDR = 6;</code>
     */
    protected $toIDR = 0.0;
    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     */
    protected $updated_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $name
     *     @type string $unit
     *     @type float $toUSD
     *     @type float $toEUR
     *     @type float $toIDR
     *     @type string $created_at
     *     @type string $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Investment\Investment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unit = 3;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>string unit = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double toUSD = 4;</code>
     * @return float
     */
    public function getToUSD()
    {
        return $this->toUSD;
    }

    /**
     * Generated from protobuf field <code>double toUSD = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setToUSD($var)
    {
        GPBUtil::checkDouble($var);
        $this->toUSD = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double toEUR = 5;</code>
     * @return float
     */
    public function getToEUR()
    {
        return $this->toEUR;
    }

    /**
     * Generated from protobuf field <code>double toEUR = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setToEUR($var)
    {
        GPBUtil::checkDouble($var);
        $this->toEUR = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double toIDR = 6;</code>
     * @return float
     */
    public function getToIDR()
    {
        return $this->toIDR;
    }

    /**
     * Generated from protobuf field <code>double toIDR = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setToIDR($var)
    {
        GPBUtil::checkDouble($var);
        $this->toIDR = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

}

