<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: investment/investment.proto

namespace Investment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>investment.InvestmentSummaryResponse</code>
 */
class InvestmentSummaryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 total_investments = 1;</code>
     */
    protected $total_investments = 0;
    /**
     * Generated from protobuf field <code>double total_invested = 2;</code>
     */
    protected $total_invested = 0.0;
    /**
     * Generated from protobuf field <code>double total_current_value = 3;</code>
     */
    protected $total_current_value = 0.0;
    /**
     * Generated from protobuf field <code>double total_profit_loss = 4;</code>
     */
    protected $total_profit_loss = 0.0;
    /**
     * Generated from protobuf field <code>double total_profit_loss_pct = 5;</code>
     */
    protected $total_profit_loss_pct = 0.0;
    /**
     * Generated from protobuf field <code>double total_sold_amount = 6;</code>
     */
    protected $total_sold_amount = 0.0;
    /**
     * Generated from protobuf field <code>double total_realized_gain = 7;</code>
     */
    protected $total_realized_gain = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total_investments
     *     @type float $total_invested
     *     @type float $total_current_value
     *     @type float $total_profit_loss
     *     @type float $total_profit_loss_pct
     *     @type float $total_sold_amount
     *     @type float $total_realized_gain
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Investment\Investment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 total_investments = 1;</code>
     * @return int
     */
    public function getTotalInvestments()
    {
        return $this->total_investments;
    }

    /**
     * Generated from protobuf field <code>int32 total_investments = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalInvestments($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_investments = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_invested = 2;</code>
     * @return float
     */
    public function getTotalInvested()
    {
        return $this->total_invested;
    }

    /**
     * Generated from protobuf field <code>double total_invested = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalInvested($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_invested = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_current_value = 3;</code>
     * @return float
     */
    public function getTotalCurrentValue()
    {
        return $this->total_current_value;
    }

    /**
     * Generated from protobuf field <code>double total_current_value = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalCurrentValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_current_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_profit_loss = 4;</code>
     * @return float
     */
    public function getTotalProfitLoss()
    {
        return $this->total_profit_loss;
    }

    /**
     * Generated from protobuf field <code>double total_profit_loss = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalProfitLoss($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_profit_loss = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_profit_loss_pct = 5;</code>
     * @return float
     */
    public function getTotalProfitLossPct()
    {
        return $this->total_profit_loss_pct;
    }

    /**
     * Generated from protobuf field <code>double total_profit_loss_pct = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalProfitLossPct($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_profit_loss_pct = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_sold_amount = 6;</code>
     * @return float
     */
    public function getTotalSoldAmount()
    {
        return $this->total_sold_amount;
    }

    /**
     * Generated from protobuf field <code>double total_sold_amount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalSoldAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_sold_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_realized_gain = 7;</code>
     * @return float
     */
    public function getTotalRealizedGain()
    {
        return $this->total_realized_gain;
    }

    /**
     * Generated from protobuf field <code>double total_realized_gain = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalRealizedGain($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_realized_gain = $var;

        return $this;
    }

}

