<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: investment/investment.proto

namespace Investment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>investment.InvestmentSold</code>
 */
class InvestmentSold extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string investment_id = 2;</code>
     */
    protected $investment_id = '';
    /**
     * Generated from protobuf field <code>string user_id = 3;</code>
     */
    protected $user_id = '';
    /**
     * Generated from protobuf field <code>double quantity = 4;</code>
     */
    protected $quantity = 0.0;
    /**
     * Generated from protobuf field <code>double sell_price = 5;</code>
     */
    protected $sell_price = 0.0;
    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>string date = 7;</code>
     */
    protected $date = '';
    /**
     * Generated from protobuf field <code>string description = 8;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double deficit = 9;</code>
     */
    protected $deficit = 0.0;
    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>.investment.AssetCode asset = 12;</code>
     */
    protected $asset = null;
    /**
     * Generated from protobuf field <code>string wallet_id = 13;</code>
     */
    protected $wallet_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $investment_id
     *     @type string $user_id
     *     @type float $quantity
     *     @type float $sell_price
     *     @type float $amount
     *     @type string $date
     *     @type string $description
     *     @type float $deficit
     *     @type string $created_at
     *     @type string $updated_at
     *     @type \Investment\AssetCode $asset
     *     @type string $wallet_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Investment\Investment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string investment_id = 2;</code>
     * @return string
     */
    public function getInvestmentId()
    {
        return $this->investment_id;
    }

    /**
     * Generated from protobuf field <code>string investment_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInvestmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->investment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_id = 3;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double quantity = 4;</code>
     * @return float
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>double quantity = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkDouble($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sell_price = 5;</code>
     * @return float
     */
    public function getSellPrice()
    {
        return $this->sell_price;
    }

    /**
     * Generated from protobuf field <code>double sell_price = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setSellPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->sell_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date = 7;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Generated from protobuf field <code>string date = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double deficit = 9;</code>
     * @return float
     */
    public function getDeficit()
    {
        return $this->deficit;
    }

    /**
     * Generated from protobuf field <code>double deficit = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setDeficit($var)
    {
        GPBUtil::checkDouble($var);
        $this->deficit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.investment.AssetCode asset = 12;</code>
     * @return \Investment\AssetCode|null
     */
    public function getAsset()
    {
        return $this->asset;
    }

    public function hasAsset()
    {
        return isset($this->asset);
    }

    public function clearAsset()
    {
        unset($this->asset);
    }

    /**
     * Generated from protobuf field <code>.investment.AssetCode asset = 12;</code>
     * @param \Investment\AssetCode $var
     * @return $this
     */
    public function setAsset($var)
    {
        GPBUtil::checkMessage($var, \Investment\AssetCode::class);
        $this->asset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 13;</code>
     * @return string
     */
    public function getWalletId()
    {
        return $this->wallet_id;
    }

    /**
     * Generated from protobuf field <code>string wallet_id = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wallet_id = $var;

        return $this;
    }

}

