// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: investment/investment.proto

package investment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_investment_investment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{0}
}

type AssetCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	ToUSD         float64                `protobuf:"fixed64,4,opt,name=toUSD,proto3" json:"toUSD,omitempty"`
	ToEUR         float64                `protobuf:"fixed64,5,opt,name=toEUR,proto3" json:"toEUR,omitempty"`
	ToIDR         float64                `protobuf:"fixed64,6,opt,name=toIDR,proto3" json:"toIDR,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCode) Reset() {
	*x = AssetCode{}
	mi := &file_investment_investment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCode) ProtoMessage() {}

func (x *AssetCode) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCode.ProtoReflect.Descriptor instead.
func (*AssetCode) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{1}
}

func (x *AssetCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AssetCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetCode) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *AssetCode) GetToUSD() float64 {
	if x != nil {
		return x.ToUSD
	}
	return 0
}

func (x *AssetCode) GetToEUR() float64 {
	if x != nil {
		return x.ToEUR
	}
	return 0
}

func (x *AssetCode) GetToIDR() float64 {
	if x != nil {
		return x.ToIDR
	}
	return 0
}

func (x *AssetCode) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AssetCode) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Investment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity         float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	InitialValuation float64                `protobuf:"fixed64,5,opt,name=initial_valuation,json=initialValuation,proto3" json:"initial_valuation,omitempty"`
	Amount           float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Date             string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Asset            *AssetCode             `protobuf:"bytes,9,opt,name=asset,proto3" json:"asset,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	WalletId         string                 `protobuf:"bytes,12,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Investment) Reset() {
	*x = Investment{}
	mi := &file_investment_investment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Investment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Investment) ProtoMessage() {}

func (x *Investment) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Investment.ProtoReflect.Descriptor instead.
func (*Investment) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{2}
}

func (x *Investment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Investment) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Investment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Investment) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Investment) GetInitialValuation() float64 {
	if x != nil {
		return x.InitialValuation
	}
	return 0
}

func (x *Investment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Investment) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Investment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Investment) GetAsset() *AssetCode {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Investment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Investment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Investment) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type InvestmentSold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvestmentId  string                 `protobuf:"bytes,2,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SellPrice     float64                `protobuf:"fixed64,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Deficit       float64                `protobuf:"fixed64,9,opt,name=deficit,proto3" json:"deficit,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Asset         *AssetCode             `protobuf:"bytes,12,opt,name=asset,proto3" json:"asset,omitempty"`
	WalletId      string                 `protobuf:"bytes,13,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestmentSold) Reset() {
	*x = InvestmentSold{}
	mi := &file_investment_investment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentSold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentSold) ProtoMessage() {}

func (x *InvestmentSold) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentSold.ProtoReflect.Descriptor instead.
func (*InvestmentSold) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{3}
}

func (x *InvestmentSold) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvestmentSold) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

func (x *InvestmentSold) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InvestmentSold) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvestmentSold) GetSellPrice() float64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *InvestmentSold) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InvestmentSold) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *InvestmentSold) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvestmentSold) GetDeficit() float64 {
	if x != nil {
		return x.Deficit
	}
	return 0
}

func (x *InvestmentSold) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InvestmentSold) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *InvestmentSold) GetAsset() *AssetCode {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *InvestmentSold) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type InvestmentID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestmentID) Reset() {
	*x = InvestmentID{}
	mi := &file_investment_investment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentID) ProtoMessage() {}

func (x *InvestmentID) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentID.ProtoReflect.Descriptor instead.
func (*InvestmentID) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{4}
}

func (x *InvestmentID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_investment_investment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{5}
}

func (x *UserID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInvestmentOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvestmentOptions) Reset() {
	*x = GetInvestmentOptions{}
	mi := &file_investment_investment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvestmentOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvestmentOptions) ProtoMessage() {}

func (x *GetInvestmentOptions) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvestmentOptions.ProtoReflect.Descriptor instead.
func (*GetInvestmentOptions) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvestmentOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserInvestmentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInvestmentListRequest) Reset() {
	*x = GetUserInvestmentListRequest{}
	mi := &file_investment_investment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInvestmentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInvestmentListRequest) ProtoMessage() {}

func (x *GetUserInvestmentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInvestmentListRequest.ProtoReflect.Descriptor instead.
func (*GetUserInvestmentListRequest) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInvestmentListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInvestmentListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserInvestmentListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserInvestmentListRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetUserInvestmentListRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *GetUserInvestmentListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetUserInvestmentListRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetInvestmentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InvestmentId  string                 `protobuf:"bytes,2,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvestmentDetailRequest) Reset() {
	*x = GetInvestmentDetailRequest{}
	mi := &file_investment_investment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvestmentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvestmentDetailRequest) ProtoMessage() {}

func (x *GetInvestmentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvestmentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetInvestmentDetailRequest) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{8}
}

func (x *GetInvestmentDetailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInvestmentDetailRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

type CreateInvestmentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Quantity         float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount           float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	InitialValuation float64                `protobuf:"fixed64,5,opt,name=initial_valuation,json=initialValuation,proto3" json:"initial_valuation,omitempty"`
	Date             string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	WalletId         string                 `protobuf:"bytes,8,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateInvestmentRequest) Reset() {
	*x = CreateInvestmentRequest{}
	mi := &file_investment_investment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvestmentRequest) ProtoMessage() {}

func (x *CreateInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvestmentRequest.ProtoReflect.Descriptor instead.
func (*CreateInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{9}
}

func (x *CreateInvestmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvestmentRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateInvestmentRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateInvestmentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateInvestmentRequest) GetInitialValuation() float64 {
	if x != nil {
		return x.InitialValuation
	}
	return 0
}

func (x *CreateInvestmentRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateInvestmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateInvestmentRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type SellInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	WalletId      string                 `protobuf:"bytes,7,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInvestmentRequest) Reset() {
	*x = SellInvestmentRequest{}
	mi := &file_investment_investment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInvestmentRequest) ProtoMessage() {}

func (x *SellInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInvestmentRequest.ProtoReflect.Descriptor instead.
func (*SellInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{10}
}

func (x *SellInvestmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SellInvestmentRequest) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *SellInvestmentRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellInvestmentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SellInvestmentRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SellInvestmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SellInvestmentRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetUserInvestmentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Investments   []*Investment          `protobuf:"bytes,1,rep,name=investments,proto3" json:"investments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInvestmentListResponse) Reset() {
	*x = GetUserInvestmentListResponse{}
	mi := &file_investment_investment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInvestmentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInvestmentListResponse) ProtoMessage() {}

func (x *GetUserInvestmentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInvestmentListResponse.ProtoReflect.Descriptor instead.
func (*GetUserInvestmentListResponse) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserInvestmentListResponse) GetInvestments() []*Investment {
	if x != nil {
		return x.Investments
	}
	return nil
}

func (x *GetUserInvestmentListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserInvestmentListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserInvestmentListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserInvestmentListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type SellInvestmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoldRecords   []*InvestmentSold      `protobuf:"bytes,1,rep,name=sold_records,json=soldRecords,proto3" json:"sold_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInvestmentResponse) Reset() {
	*x = SellInvestmentResponse{}
	mi := &file_investment_investment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInvestmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInvestmentResponse) ProtoMessage() {}

func (x *SellInvestmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInvestmentResponse.ProtoReflect.Descriptor instead.
func (*SellInvestmentResponse) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{12}
}

func (x *SellInvestmentResponse) GetSoldRecords() []*InvestmentSold {
	if x != nil {
		return x.SoldRecords
	}
	return nil
}

type InvestmentSummaryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalInvestments   int32                  `protobuf:"varint,1,opt,name=total_investments,json=totalInvestments,proto3" json:"total_investments,omitempty"`
	TotalInvested      float64                `protobuf:"fixed64,2,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	TotalCurrentValue  float64                `protobuf:"fixed64,3,opt,name=total_current_value,json=totalCurrentValue,proto3" json:"total_current_value,omitempty"`
	TotalProfitLoss    float64                `protobuf:"fixed64,4,opt,name=total_profit_loss,json=totalProfitLoss,proto3" json:"total_profit_loss,omitempty"`
	TotalProfitLossPct float64                `protobuf:"fixed64,5,opt,name=total_profit_loss_pct,json=totalProfitLossPct,proto3" json:"total_profit_loss_pct,omitempty"`
	TotalSoldAmount    float64                `protobuf:"fixed64,6,opt,name=total_sold_amount,json=totalSoldAmount,proto3" json:"total_sold_amount,omitempty"`
	TotalRealizedGain  float64                `protobuf:"fixed64,7,opt,name=total_realized_gain,json=totalRealizedGain,proto3" json:"total_realized_gain,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvestmentSummaryResponse) Reset() {
	*x = InvestmentSummaryResponse{}
	mi := &file_investment_investment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentSummaryResponse) ProtoMessage() {}

func (x *InvestmentSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentSummaryResponse.ProtoReflect.Descriptor instead.
func (*InvestmentSummaryResponse) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{13}
}

func (x *InvestmentSummaryResponse) GetTotalInvestments() int32 {
	if x != nil {
		return x.TotalInvestments
	}
	return 0
}

func (x *InvestmentSummaryResponse) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *InvestmentSummaryResponse) GetTotalCurrentValue() float64 {
	if x != nil {
		return x.TotalCurrentValue
	}
	return 0
}

func (x *InvestmentSummaryResponse) GetTotalProfitLoss() float64 {
	if x != nil {
		return x.TotalProfitLoss
	}
	return 0
}

func (x *InvestmentSummaryResponse) GetTotalProfitLossPct() float64 {
	if x != nil {
		return x.TotalProfitLossPct
	}
	return 0
}

func (x *InvestmentSummaryResponse) GetTotalSoldAmount() float64 {
	if x != nil {
		return x.TotalSoldAmount
	}
	return 0
}

func (x *InvestmentSummaryResponse) GetTotalRealizedGain() float64 {
	if x != nil {
		return x.TotalRealizedGain
	}
	return 0
}

type GetAssetCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetCodes    []*AssetCode           `protobuf:"bytes,1,rep,name=asset_codes,json=assetCodes,proto3" json:"asset_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetCodesResponse) Reset() {
	*x = GetAssetCodesResponse{}
	mi := &file_investment_investment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetCodesResponse) ProtoMessage() {}

func (x *GetAssetCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetCodesResponse.ProtoReflect.Descriptor instead.
func (*GetAssetCodesResponse) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{14}
}

func (x *GetAssetCodesResponse) GetAssetCodes() []*AssetCode {
	if x != nil {
		return x.AssetCodes
	}
	return nil
}

type AssetCodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCodeID) Reset() {
	*x = AssetCodeID{}
	mi := &file_investment_investment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCodeID) ProtoMessage() {}

func (x *AssetCodeID) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCodeID.ProtoReflect.Descriptor instead.
func (*AssetCodeID) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{15}
}

func (x *AssetCodeID) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListAssetCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetCodesRequest) Reset() {
	*x = ListAssetCodesRequest{}
	mi := &file_investment_investment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetCodesRequest) ProtoMessage() {}

func (x *ListAssetCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetCodesRequest.ProtoReflect.Descriptor instead.
func (*ListAssetCodesRequest) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{16}
}

func (x *ListAssetCodesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetCodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetCodesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListAssetCodesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListAssetCodesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListAssetCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetCodes    []*AssetCode           `protobuf:"bytes,1,rep,name=asset_codes,json=assetCodes,proto3" json:"asset_codes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetCodesResponse) Reset() {
	*x = ListAssetCodesResponse{}
	mi := &file_investment_investment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetCodesResponse) ProtoMessage() {}

func (x *ListAssetCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_investment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetCodesResponse.ProtoReflect.Descriptor instead.
func (*ListAssetCodesResponse) Descriptor() ([]byte, []int) {
	return file_investment_investment_proto_rawDescGZIP(), []int{17}
}

func (x *ListAssetCodesResponse) GetAssetCodes() []*AssetCode {
	if x != nil {
		return x.AssetCodes
	}
	return nil
}

func (x *ListAssetCodesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAssetCodesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetCodesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetCodesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

var File_investment_investment_proto protoreflect.FileDescriptor

const file_investment_investment_proto_rawDesc = "" +
	"\n" +
	"\x1binvestment/investment.proto\x12\n" +
	"investment\"\a\n" +
	"\x05Empty\"\xc7\x01\n" +
	"\tAssetCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x14\n" +
	"\x05toUSD\x18\x04 \x01(\x01R\x05toUSD\x12\x14\n" +
	"\x05toEUR\x18\x05 \x01(\x01R\x05toEUR\x12\x14\n" +
	"\x05toIDR\x18\x06 \x01(\x01R\x05toIDR\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xe8\x02\n" +
	"\n" +
	"Investment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12+\n" +
	"\x11initial_valuation\x18\x05 \x01(\x01R\x10initialValuation\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12+\n" +
	"\x05asset\x18\t \x01(\v2\x15.investment.AssetCodeR\x05asset\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\twallet_id\x18\f \x01(\tR\bwalletId\"\x89\x03\n" +
	"\x0eInvestmentSold\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinvestment_id\x18\x02 \x01(\tR\finvestmentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x05 \x01(\x01R\tsellPrice\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x18\n" +
	"\adeficit\x18\t \x01(\x01R\adeficit\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12+\n" +
	"\x05asset\x18\f \x01(\v2\x15.investment.AssetCodeR\x05asset\x12\x1b\n" +
	"\twallet_id\x18\r \x01(\tR\bwalletId\"\x1e\n" +
	"\fInvestmentID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x14GetInvestmentOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xcc\x01\n" +
	"\x1cGetUserInvestmentListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\"Z\n" +
	"\x1aGetInvestmentDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rinvestment_id\x18\x02 \x01(\tR\finvestmentId\"\xfa\x01\n" +
	"\x17CreateInvestmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12+\n" +
	"\x11initial_valuation\x18\x05 \x01(\x01R\x10initialValuation\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\twallet_id\x18\b \x01(\tR\bwalletId\"\xd6\x01\n" +
	"\x15SellInvestmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\twallet_id\x18\a \x01(\tR\bwalletId\"\xc1\x01\n" +
	"\x1dGetUserInvestmentListResponse\x128\n" +
	"\vinvestments\x18\x01 \x03(\v2\x16.investment.InvestmentR\vinvestments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"W\n" +
	"\x16SellInvestmentResponse\x12=\n" +
	"\fsold_records\x18\x01 \x03(\v2\x1a.investment.InvestmentSoldR\vsoldRecords\"\xda\x02\n" +
	"\x19InvestmentSummaryResponse\x12+\n" +
	"\x11total_investments\x18\x01 \x01(\x05R\x10totalInvestments\x12%\n" +
	"\x0etotal_invested\x18\x02 \x01(\x01R\rtotalInvested\x12.\n" +
	"\x13total_current_value\x18\x03 \x01(\x01R\x11totalCurrentValue\x12*\n" +
	"\x11total_profit_loss\x18\x04 \x01(\x01R\x0ftotalProfitLoss\x121\n" +
	"\x15total_profit_loss_pct\x18\x05 \x01(\x01R\x12totalProfitLossPct\x12*\n" +
	"\x11total_sold_amount\x18\x06 \x01(\x01R\x0ftotalSoldAmount\x12.\n" +
	"\x13total_realized_gain\x18\a \x01(\x01R\x11totalRealizedGain\"O\n" +
	"\x15GetAssetCodesResponse\x126\n" +
	"\vasset_codes\x18\x01 \x03(\v2\x15.investment.AssetCodeR\n" +
	"assetCodes\"!\n" +
	"\vAssetCodeID\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x98\x01\n" +
	"\x15ListAssetCodesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\"\xb8\x01\n" +
	"\x16ListAssetCodesResponse\x126\n" +
	"\vasset_codes\x18\x01 \x03(\v2\x15.investment.AssetCodeR\n" +
	"assetCodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages2\xcd\x06\n" +
	"\x11InvestmentService\x12L\n" +
	"\x0eGetInvestments\x12 .investment.GetInvestmentOptions\x1a\x16.investment.Investment0\x01\x12B\n" +
	"\x12GetUserInvestments\x12\x12.investment.UserID\x1a\x16.investment.Investment0\x01\x12l\n" +
	"\x15GetUserInvestmentList\x12(.investment.GetUserInvestmentListRequest\x1a).investment.GetUserInvestmentListResponse\x12U\n" +
	"\x13GetInvestmentDetail\x12&.investment.GetInvestmentDetailRequest\x1a\x16.investment.Investment\x12O\n" +
	"\x10CreateInvestment\x12#.investment.CreateInvestmentRequest\x1a\x16.investment.Investment\x12W\n" +
	"\x0eSellInvestment\x12!.investment.SellInvestmentRequest\x1a\".investment.SellInvestmentResponse\x12Q\n" +
	"\x14GetInvestmentSummary\x12\x12.investment.UserID\x1a%.investment.InvestmentSummaryResponse\x12E\n" +
	"\rGetAssetCodes\x12\x11.investment.Empty\x1a!.investment.GetAssetCodesResponse\x12W\n" +
	"\x0eListAssetCodes\x12!.investment.ListAssetCodesRequest\x1a\".investment.ListAssetCodesResponse\x12D\n" +
	"\x12GetAssetCodeDetail\x12\x17.investment.AssetCodeID\x1a\x15.investment.AssetCodeB6Z4github.com/MuhammadMiftaa/Refina-Protobuf/investmentb\x06proto3"

var (
	file_investment_investment_proto_rawDescOnce sync.Once
	file_investment_investment_proto_rawDescData []byte
)

func file_investment_investment_proto_rawDescGZIP() []byte {
	file_investment_investment_proto_rawDescOnce.Do(func() {
		file_investment_investment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_investment_investment_proto_rawDesc), len(file_investment_investment_proto_rawDesc)))
	})
	return file_investment_investment_proto_rawDescData
}

var file_investment_investment_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_investment_investment_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: investment.Empty
	(*AssetCode)(nil),                     // 1: investment.AssetCode
	(*Investment)(nil),                    // 2: investment.Investment
	(*InvestmentSold)(nil),                // 3: investment.InvestmentSold
	(*InvestmentID)(nil),                  // 4: investment.InvestmentID
	(*UserID)(nil),                        // 5: investment.UserID
	(*GetInvestmentOptions)(nil),          // 6: investment.GetInvestmentOptions
	(*GetUserInvestmentListRequest)(nil),  // 7: investment.GetUserInvestmentListRequest
	(*GetInvestmentDetailRequest)(nil),    // 8: investment.GetInvestmentDetailRequest
	(*CreateInvestmentRequest)(nil),       // 9: investment.CreateInvestmentRequest
	(*SellInvestmentRequest)(nil),         // 10: investment.SellInvestmentRequest
	(*GetUserInvestmentListResponse)(nil), // 11: investment.GetUserInvestmentListResponse
	(*SellInvestmentResponse)(nil),        // 12: investment.SellInvestmentResponse
	(*InvestmentSummaryResponse)(nil),     // 13: investment.InvestmentSummaryResponse
	(*GetAssetCodesResponse)(nil),         // 14: investment.GetAssetCodesResponse
	(*AssetCodeID)(nil),                   // 15: investment.AssetCodeID
	(*ListAssetCodesRequest)(nil),         // 16: investment.ListAssetCodesRequest
	(*ListAssetCodesResponse)(nil),        // 17: investment.ListAssetCodesResponse
}
var file_investment_investment_proto_depIdxs = []int32{
	1,  // 0: investment.Investment.asset:type_name -> investment.AssetCode
	1,  // 1: investment.InvestmentSold.asset:type_name -> investment.AssetCode
	2,  // 2: investment.GetUserInvestmentListResponse.investments:type_name -> investment.Investment
	3,  // 3: investment.SellInvestmentResponse.sold_records:type_name -> investment.InvestmentSold
	1,  // 4: investment.GetAssetCodesResponse.asset_codes:type_name -> investment.AssetCode
	1,  // 5: investment.ListAssetCodesResponse.asset_codes:type_name -> investment.AssetCode
	6,  // 6: investment.InvestmentService.GetInvestments:input_type -> investment.GetInvestmentOptions
	5,  // 7: investment.InvestmentService.GetUserInvestments:input_type -> investment.UserID
	7,  // 8: investment.InvestmentService.GetUserInvestmentList:input_type -> investment.GetUserInvestmentListRequest
	8,  // 9: investment.InvestmentService.GetInvestmentDetail:input_type -> investment.GetInvestmentDetailRequest
	9,  // 10: investment.InvestmentService.CreateInvestment:input_type -> investment.CreateInvestmentRequest
	10, // 11: investment.InvestmentService.SellInvestment:input_type -> investment.SellInvestmentRequest
	5,  // 12: investment.InvestmentService.GetInvestmentSummary:input_type -> investment.UserID
	0,  // 13: investment.InvestmentService.GetAssetCodes:input_type -> investment.Empty
	16, // 14: investment.InvestmentService.ListAssetCodes:input_type -> investment.ListAssetCodesRequest
	15, // 15: investment.InvestmentService.GetAssetCodeDetail:input_type -> investment.AssetCodeID
	2,  // 16: investment.InvestmentService.GetInvestments:output_type -> investment.Investment
	2,  // 17: investment.InvestmentService.GetUserInvestments:output_type -> investment.Investment
	11, // 18: investment.InvestmentService.GetUserInvestmentList:output_type -> investment.GetUserInvestmentListResponse
	2,  // 19: investment.InvestmentService.GetInvestmentDetail:output_type -> investment.Investment
	2,  // 20: investment.InvestmentService.CreateInvestment:output_type -> investment.Investment
	12, // 21: investment.InvestmentService.SellInvestment:output_type -> investment.SellInvestmentResponse
	13, // 22: investment.InvestmentService.GetInvestmentSummary:output_type -> investment.InvestmentSummaryResponse
	14, // 23: investment.InvestmentService.GetAssetCodes:output_type -> investment.GetAssetCodesResponse
	17, // 24: investment.InvestmentService.ListAssetCodes:output_type -> investment.ListAssetCodesResponse
	1,  // 25: investment.InvestmentService.GetAssetCodeDetail:output_type -> investment.AssetCode
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_investment_investment_proto_init() }
func file_investment_investment_proto_init() {
	if File_investment_investment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_investment_investment_proto_rawDesc), len(file_investment_investment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_investment_investment_proto_goTypes,
		DependencyIndexes: file_investment_investment_proto_depIdxs,
		MessageInfos:      file_investment_investment_proto_msgTypes,
	}.Build()
	File_investment_investment_proto = out.File
	file_investment_investment_proto_goTypes = nil
	file_investment_investment_proto_depIdxs = nil
}
