<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: investment/investment.proto

namespace Investment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>investment.SellInvestmentResponse</code>
 */
class SellInvestmentResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .investment.InvestmentSold sold_records = 1;</code>
     */
    private $sold_records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Investment\InvestmentSold>|\Google\Protobuf\Internal\RepeatedField $sold_records
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Investment\Investment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .investment.InvestmentSold sold_records = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSoldRecords()
    {
        return $this->sold_records;
    }

    /**
     * Generated from protobuf field <code>repeated .investment.InvestmentSold sold_records = 1;</code>
     * @param array<\Investment\InvestmentSold>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSoldRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Investment\InvestmentSold::class);
        $this->sold_records = $arr;

        return $this;
    }

}

